### ISSUE TITLE
Separating code per-precision ? 

### ISSUE THREAD

**Issue by hominhquan** [flame/blis#141]
Firstly, I think that this request can make a long debate, and if feasible, 
will involve big change in code.

The current BLIS control trees and execution flow for the four precisions (sdcz) 
are generalized into one obj_t API and only gets dispatched at 
the bottom leaf by static array of function pointers depending on `dt`. 
If I understand, the reason of this structuration is because we can not write 
C++ templates in C.

The point is this makes it impossible for the linker to strip unused code at link time. 
Given the large memory of conventional CPU systems, this is not a problem. 
But, for example, on an embedded hardware, the binary size of 1.3 MB is sometimes 
hard to afford. 

So I just want to know your opinions about separating the existing C code 
(code bloat forehead) or templating by C++ ?

**Comment by devinamatthews** [comment]
Perhaps the same effect could be more easily achieved by allowing selective disabling of data types/operations?

**Comment by hominhquan** [comment]
This could be a solution, but partially. If I compile BLIS only for S+D, a Sgemm "helloworld" binary still contains all Dgemm operations. 

Or compiling one library per datatype could also be a solution (lib[s|d|c|z]blis.a) ?

**Comment by devinamatthews** [comment]
One could always just compile a "local" version of BLIS with just the required operations for programs that really need to squeeze down, although I see what you mean about having the linker do it being easier.

Technically, I think your suggestion is possible but not likely to be pursued. This would have several ramifications:

1) It would be a lot of work (duh). Specifically it would mean making *everything* into a template/macro instead of just the computational bits. This also means *larger* library size for shared libraries.
2) This would really make mixed-precision hard, which we would like to support (someday).
3) There would still need to be some arrays of pointers around, e.g. for selecting the HW kernels (this part of the code is actually going irreversibly in the opposite direction as you're suggesting), so code size still wouldn't necessarily be as minimal as possible.

Perhaps you could share some details of the platform that you're working on and what you're trying to do there with BLIS? If you only need, say, SGEMM for one architecture, then you can actually pull bits out of BLIS and write a one- or two-function implementation in a few hundred LOC. We might be able to help with something like this.

**Comment by jeffhammond** [comment]
This seems like a perfectly reasonable thing to implement in a fork of the main project.  Embedded hardware creates lots of constraints that don't apply elsewhere, so software contortions to support this setting should not be implemented in packages that target broad use.

**Comment by hominhquan** [comment]
@devinamatthews  I'm working on a full port of BLIS on the [Kalray MPPA](http://www.kalrayinc.com/IMG/pdf/FLYER_MPPA_MANYCORE.pdf), on which 
BLIS would run on a single cluster (a 16-core CPU-like) with 2MB of 
on-chip memory (SMEM) to store the binary code and L2 data cache. 
An Sgemm example takes 1.3 MB in size, so not much space left for 
data.

@jeffhammond I will consider this. Thanks.

**Comment by fgvanzee** [comment]
@hominhquan Thanks for your comments. You make a good point by implying that a netlib-style solution would allow the linker to weed out the object files whose symbols aren't referenced, thus helping reduce your executable code size. This sort of all goes back to the tradeoff spectrum where you have "collection of routines" on one end and "integrated framework" on the other. BLIS happens to fall closer to the latter end, and in doing so derives certain benefits and incurs certain costs.

@devinamatthews If we magically had a C++ implementation of BLIS (one that was sanely-structured), would this issue be more tractable?

**Comment by hominhquan** [comment]
From what I see from how "templating" was done in BLIS by macros, I think that the rest of BLIS can be templated with the same technique, without particular difficulty (in my eyes), despite certain work. 
Anyway, I know that this is a big decision that changes a lot of things, while the issue only affects embedded platforms, so I understand that the answer would be "no". 

PS Out-of-topic : I find C++  template (and recently Rust) helpful to implement polymorphism (e.g BLAS) lib (like [clBlast](https://github.com/CNugteren/CLBlast))

**Comment by jeffhammond** [comment]
@hominhquan https://github.com/devinamatthews/tblis is the closets approximation to "BLIS in C++" if you are interested in C++ polymorphism.  Obviously, @devinamatthews will be able to comment on whether or not this has the potential to meet your needs.  However, if your goal is a minimal binary, I'm not sure that C++ is actually going to help, given that the runtime library is not small.

**Comment by devinamatthews** [comment]
**TBLIS** as it is currently implemented does not help with this, because all of the functionality is hidden behind a unified C interface which uses function pointers internally. @hominhquan please look at https://github.com/devinamatthews/molssi-sss-2017/blob/master/optimizing_gemm/my_dgemm_8.cxx for an example of high-performance `dgemm` (Haswell) in a single file (<400 lines).

If this looks doable from your perspective, I think it is the best way to truly minimize binary size. We might be able to assist in coming up with example implementations for other BLAS operations as well.

NOTE: this example doesn't include threading, but you can basically just do nested OpenMP (with synchronization).

**Comment by devinamatthews** [comment]
BTW, "Hello World" with the above `dgemm` is about 16K.

**Comment by fgvanzee** [comment]
@devinamatthews Just to clarify, does your hello world actually call `dgemm()`, or were you illustrating the "base" code size with no outside library function calls?

**Comment by devinamatthews** [comment]
This is the DLA "hello world" where you time dgemm for some range of m=n=k.

**Comment by fgvanzee** [comment]
@devinamatthews Understood, thanks. I'm actually impressed that you manage to get it down to 16K.
@hominhquan 16 kilobytes seems quite small. Would this work for your purposes?

**Comment by hominhquan** [comment]
@jeffhammond Thank you for the reference. 
@devinamatthews Thanks, your C++ implementation and its size is very interesting. @fgvanzee The point is that I need at least the level-3 in sd (ideally sdcz and mixed half-float in the future). I just don't know how far we can go to implement them separately one-by-one, parameter-by-parameter, without falling back to the same process as Netlib. And I could not ask Devin for all of them, either. 

I think a fork of BLIS in which everything is "template"-ed, either in C or C++ will be the solution which fit the most, at least for me, and later for the embedded world. How do you guys think ? @figual ?

**Comment by devinamatthews** [comment]
Just one minor note: the sort of implementation I referenced can also be templated (except for the microkernel) to get around the sdcz issue.

**Comment by hominhquan** [comment]
For the micro-kernel, I think that solution is somewhere out there, with C++ function overloading or _Generic type macro in C99 (gcc >= 4.9)
http://en.cppreference.com/w/c/language/generic

**Comment by jeffhammond** [comment]
@hominhquan `_Generic` is C11, not C99, and is thus untenable until there is broad support for this standard, although I think it is already supported by every compiler vendor of interest (GCC, Clang, Intel, ...), just only in recent versions.  The only library where this feature is used today (AFAIK) is OpenSHMEM.  In that context, we've found some aspects of it more complicated that what one concludes at first glance.  Unless C++ is verboten, I think it is the right way to implement polymorphism.

**Comment by devinamatthews** [comment]
@hominhquan a new solution popped up on (blis-discuss)[https://groups.google.com/forum/#!topic/blis-discuss/_p-cCwkK9FI].
