### ISSUE TITLE
BLIS should automatically self-initialize

### ISSUE THREAD

**Issue by fgvanzee** [flame/blis#158]
Users of the BLAS-like and object-based APIs in BLIS are probably familiar with the fact that the application/user is expected to call `bli_init()` prior to any other BLIS function, and is expected to call `bli_finalize()` after BLIS is no longer needed (or, if it coincides with the end of your program, `bli_finalize()` is not needed and therefore optional, though historically we have always encouraged calling both explicitly).

The first, most obvious problem with this usage is that it's annoying. Callers of the BLAS compatibility layer are not required to first invoke `bli_init()`; so why should users of the other two APIs have to go through the extra hassle of explicitly initializing the library?

A second, more subtle problem is that the `bli_init()` function call should really happen outside of an application's threaded region, which may no be convenient and/or feasible for the application. Yes, allowing the parallel region to encompass the `bli_init()/bli_finalize() span of code` looks possible from afar; after all, we try to make `bli_init()` thread-safe. (The "call it exactly once" mutual exclusion is implemented within BLIS.) But things suddenly get nasty if two or more application threads--in addition to calling `bli_init()`--call `bli_finalize()`. The finalization itself should, in theory, happen in an orderly, predictable fashion. However, what if thread 0 finishes its work early and attempts to finalize the library while thread 1 is still _using_ BLIS's internal resources? [1] Obviously this is not what we want to allow.

I propose a new regime, which calls for BLIS to initialize itself whenever necessary. Furthermore, BLIS will _stay initialized_ indefinitely. Experts can always call a function (e.g. `bli_finalize()`) to manually finalize the library and trigger the freeing of resources, though this usage would not be encouraged or recommended for normal/casual use. However, appropriate use cases exist. For example, consider a memory-constrained application where all of the DLA (or at least, all of the BLAS-like DLA) occurs exclusively early on in the program. 

After internal discussions, I plan to implement this functionality by using `pthread_once()` to guarantee that `bli_init()` is called exactly once (by the first thread to call a BLIS function). Granted, it creates a dependency on a pthreads implementation, even when multithreading is disabled. But our two most common target environments--GNU/Linux and OS X--both provide POSIX threads by default, so we are okay with this.

Comments are invited/welcome.

[1] Credit goes to Nisanth Padinharepatt of AMD for identifying and reporting this race condition.

**Comment by jeffhammond** [comment]
C11 has call_once, C++11 has std::call_once, and Windows has something
similar. Only Solaris lacks an equivalent of pthread_once. Just FYI.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fgvanzee** [comment]
@jeffhammond Thanks for pointing that out. If BLIS assumed C11, I would much rather use an in-language feature to implement self-initialization. However, we're probably several years out from where I would be comfortable requiring C11 support.

Also, are you asserting that Solaris does not include a pthreads implementation?

**Comment by jeffhammond** [comment]
@fgvanzee I was referring to the Oracle documentation that the Solaris threads API does not contain an equivalent to `pthread_once`.  I don't know if Solaris supports Pthreads or C11.

* https://docs.oracle.com/cd/E19455-01/806-5257/6je9h033p/index.html

**Comment by fgvanzee** [comment]
@jeffhammond Understood. Thanks for the clarification.

**Comment by devinamatthews** [comment]
@jeffhammond looks like it does: https://docs.oracle.com/cd/E19120-01/open.solaris/816-5137/tlib-43636/index.html.

C11 is probably a no-go since support is seriously lacking and you can't even count on things like complex numbers.

**Comment by jeffhammond** [comment]
@devinamatthews The key issue for C11 threads is the library, not the compiler.  [MUSL](musl-libc.org) supports C11 threads and is well-maintained.  However, you'll run into trouble if you use non-standard, glibc-specific features in BLIS.

**Comment by fgvanzee** [comment]
Quick update: This feature is now implemented on the `selfinit` branch, starting with commit 70640a3.

I didn't insert `bli_init_once()` calls into **every** function that I could have, in order to avoid unnecessary overhead. It made me realize that I was only inserting the initialization calls into functions that I considered to be "user" functions--that is, those that a user would be reasonably justified in calling--and that ideally I would publish a list of all such functions.

**Comment by hominhquan** [comment]
Thanks Field for the post. I agree with the idea to make `bli_init` thread-safe. I would like to share my some thinking about it:

- AFAI understand, we want to allow user to create N threads, each one is calling some individual work (e.g `bli_gemm`)}. Each of these `bli_gemm` can also create their own sub-threads (if enabled). I would call this config the N-group situation. Only threads within a group share/do the same "user" work (like normal BLIS as we know). Then, groups are sharing only the internal BLIS data structures (by `bli_init`), but not sharing any "user" work (the new mode we are wanting to support).

- To make it easy, given N = 2 and let assume the thread 0 wins and begins the real initialization stuffs. 
A possible pathological case here is that thread 1 arrives when the init is being done by the thread 0 but **not** finished yet, and so thread 1 should wait for that. This is valid only at the first round.

- I took a look at your commit. Setting `bli_is_init` to TRUE **before** performing init stuffs can be dangerous in the above mentioned case. And, even if we place the `bli_is_init = TRUE` after all the init stuffs, it may not be enough either. Because here we should need two stateful variables: 
(1) "done" and (2) "being-done". The thread 1 should look at the "being-done" variable as well, before quitting from the `bli_init_once` function.

- These two stateful variables would have been integrated actually in the `pthread_once_t` type. But, since Pthreads is implementation-dependant, nothing warranties that this is the case:
  + I saw one pthread header with this : (and is a good one)
```
struct pthread_once {
  volatile int done;        // Indicates if user function executed
  int started;              // First thread to increment this value 
                            // to zero executes the user function
};
typedef struct pthread_once pthread_once_t;
```
-  + and another simply with this: (and for me, is not a good one)
```
typedef int pthread_once_t;
```

- I suggest we should have two internal stateful variables in BLIS for this, for example:
`bli_is_init` (== done) and `bli_is_being_init` (== started)

Quan

**Comment by devinamatthews** [comment]
@hominhquan is right, but perhaps I can clarify a bit:

1. `bli_is_init` currently serves the purpose of preventing recursive calls to `pthread_once`, and must be set (as it is currently) before initialization begins in order to work correctly.
2. This does *not* guarantee the correct behavior when `bli_init_once` is called concurrently from two threads, since the second thread may see `bli_is_init` has been set and return before initialization is complete.
    - (This is actually caused explicitly by introducing `bli_is_init` and would not be a problem for a bare `pthread_once`.)
3. In order to prevent the problem in 2., one would need to set `bli_is_init` (or another similar variable) *after initialization is complete* and *with the proper memory ordering constraints*.
4. Therefore in order to address both problems, two variables are needed. I don't think additional memory ordering constraints are needed for the current usage of `bli_is_init` but it wouldn't hurt.
5. However, I think the design leading to the possibility of recursive `pthread_once` calls is the real problem. An object-oriented design according to the mantra "protect the *data* and not the *operation*" would be much cleaner.

**Comment by hominhquan** [comment]
In my head, `pthread_once` would be as simple as an atomic compare-and-swap on the "started", with one branch launching the init_routine and another branch polling on the "done" status.

But, yes, avoiding excessive (or recursive) `pthread_once` would be preferable.

**Comment by fgvanzee** [comment]
@hominhquan Thanks for pointing this out. The **only** reason I used the `bli_is_init` flag was to prevent the recursive behavior (which apparently results in execution hanging with the GNU implementation of pthreads). I would rather not use any such flags at all and solely rely on `pthread_once()`.

I've spoken to Devin, and we think we can get around this by statically initializing the scalar constants in `bli_const.c`. That will eliminate the opportunity for recursion (or at least, the one I was aware of), and hence no use for `bli_is_init`.

**Comment by fgvanzee** [comment]
This feature has been implemented; I'm ready to close.
