### ISSUE TITLE
query about arm64 support

### ISSUE THREAD

**Issue by loveshack** [flame/blis#172]
It would be useful to have a note on the scope of arm64 support for people who aren't familiar with the instruction sets. Will cortexa57 work on any aarch64 (in Fedora architecture-labelling terms, or Debian arm64)?  If not, it would be useful to have a target like "arm64" which includes "generic", like arm32, to avoid using generic for aarch64 packages.

**Comment by devinamatthews** [comment]
The cortex-a57 config should for for any aarch64 target, although it won't be optimal for other chips (better than generic, though). I believe it has also been tested (real-world) on A53.

@fgvanzee's commit 1a30317 should fix the missing "arm64" family problem, but I'll leave this open until it is better tested (incl. arm32) and merged to master.

**Comment by loveshack** [comment]
> @fgvanzee's commit 1a30317 should fix the missing "arm64" family
> problem, but I'll leave this open until it is better tested
> (incl. arm32) and merged to master.

Ah, thanks.  I didn't think to look in dev.  I have some rpm packaging
done, so I could test on whatever the arm64 (or arm32) hardware is in
the Fedora build system, if that's helpful.

**Comment by fgvanzee** [comment]
@loveshack Yeah, sorry for any confusion. We try to only commit things to `master` that we are quite confident are already working. This ARM stuff is classic "we have no idea if it works yet" type work since, in practice, we only have emulators to work with--and even that, Devin only brought to my attention this morning. (I had to spoof `/proc/cpuinfo` and run the CPUID code in a play sandbox just to get that code up and running.)

**Comment by fgvanzee** [comment]
@loveshack Closing. Please let us know if there's anything left unresolved of this issue.
