### ISSUE TITLE
linking problems for dynamic target

### ISSUE THREAD

**Issue by iotamudelta** [flame/blis#179]
Hi, on FreeBSD with clang as the compiler and LLD 6.0.0 as linker, I get the following error (sorry for crappy formatting):

Archiving lib/x86_64/libblis.a                                                                                                                                                                          
Dynamically linking lib/x86_64/libblis.so                                                                                                                                                                                                    
/usr/bin/ld: error: can't create dynamic relocation R_X86_64_PC32 against symbol                                                                                                                                                             : bli_check_noninteger_object in readonly segment; recompile object files with -                                                                                                                                                             fPIC                                                                                            
>>> defined in obj/x86_64/frame/base/bli_check.o                                                                                                                                                                                             
>>> referenced by frame/0/bli_l0_check.c                                                                                                                                                                                                     
>>>               obj/x86_64/frame/0/bli_l0_check.o:(bli_l0_xxsc_check)                                                                                                                                                                      

Looks like that one object misses fPIC in it's compile stage. I've tried to find it but haven't succeeded.

**Comment by fgvanzee** [comment]
Thanks @iotamudelta. I'll look into this.

**Comment by fgvanzee** [comment]
@iotamudelta Hmm, I tried `./configure --enable-shared x86_64; make` and cannot reproduce the linker error. Furthermore, when I recompile via `make V=1`, I can't find any objects that don't get compiled with `-fPIC`.

Would you mind rebuilding everything, starting with `make distclean`? When you compile, please use `V=1` to enable verbosity and also redirect your `make` stdout to a file so we can comb through it if needed.

```

**Comment by iotamudelta** [comment]
@fgvanzee this is for the FreeBSD port. Please find compile log attached.

Configure is with--enable-blas --prefix=/usr/local  --enable-shared --enable-static  -t pthreads --enable-cblas x86_64 . This is with LLVM5 as the compiler, LLD6 as the linker.

[VERBOSE_COMPILE.txt](https://github.com/flame/blis/files/1850324/VERBOSE_COMPILE.txt)

**Comment by fgvanzee** [comment]
@iotamudelta I've combed through your configuration/compilation log. It was very useful--thank you.

The version you are using has a bug that has since been fixed. Please try the head of `master` for the bugfix you seek as well as many other improvements. (The last month has seen a lot of activity.)

If you need me to bump the version number to justify using the more recent code, I can do so. (I was planning to release 0.3.1 in the next week or so.)

**Comment by iotamudelta** [comment]
@fgvanzee indeed, a later revision works. Is it intended that the number of files is reduced dramatically now? I only get:

include/blis/blis.h
include/blis/cblas.h
lib/libblis.a
lib/libblis.so

as installed - used to get a whole range of include/blis/bli_*.h files.

Don't worry about a new release just for this, we are not restricted to that as long as the code we include in the FreeBSD ports is "stable".

**Comment by fgvanzee** [comment]
@iotamudelta Yes, it is definitely intended. After running `./configure`, just before compilation begins, you'll notice a stage that proceeds like this:
```
Generating monolithic blis.h.............................................................
.........................................................................................
.........................................................................................
.........................................................................................
.............................................................................
```
I wrote a script, `flatten-headers.py` (and a companion `flatten-headers.sh` for environments where python isn't available) that recursively inlines all `.h` header files that are `#included` from a top-level header, such as `blis.h`. I did this to make it easier to manage/deploy/distribute the build products of a BLIS installation. (Originally, `cblas.h` was just another one of these aforementioned headers that was inlined into a monolithic `blis.h`. But then I realized this wouldn't work for legacy CBLAS applications since they expect to be able to `#include cblas.h`, hence why I generate it as a separate file.)

As for when the code is "stable", it's not something I can say for sure except in hindsight. I strive for the `master` branch to never be "broken" with the exception of situations where bugs have been reported but not yet fixed.

I plan to release 0.3.1 soon. That will be another natural sync point for package managers such as yourself.
