### ISSUE TITLE
config: --libdir

### ISSUE THREAD

**Issue by nschloe** [flame/blis#195]
I was just looking into creating a Debian package for BLIS and found that `configure` is a little non-standard (read: not line autotools ./configure).  In particular, the libdir needs to be set to `--libdir=/usr/lib/x86_64-linux-gnu` which I think is not possible right now.

**Comment by fgvanzee** [comment]
Thanks for this feedback, @nschloe . You're right that BLIS's `configure` is somewhat non-standard (at least in the sense that it does not closely conform to `autoconf`-created scripts).

Adding a `--libdir` option is certainly something I can work on, especially if it facilitates the creation of additional packages.

Because I've never used `--libdir` (though I've used `--prefix` many times), I just want to clarify what you expect from it. I'm assuming that it is simply the directory in which static or shared libraries are installed? I suppose while I'm at it, I should provide an `--includedir` option to do the same for header files. Those are the only two build products created by BLIS for the moment, so I think that should cover everything.

**Comment by nschloe** [comment]
> I'm assuming that it is simply the directory in which static or shared libraries are installed?

Indeed, overriding whatever is specified via `--prefix`.

> Those are the only two build products created by BLIS for the moment

Alright, yeah. For future reference, the full default autotools config line is
```
./configure \
   --build=x86_64-linux-gnu \
   --prefix=/usr \
   --includedir=\${prefix}/include \
   --mandir=\${prefix}/share/man \
   --infodir=\${prefix}/share/info \
   --sysconfdir=/etc \
   --localstatedir=/var \
   --disable-silent-rules \
   --libdir=\${prefix}/lib/x86_64-linux-gnu \
   --libexecdir=\${prefix}/lib/x86_64-linux-gnu \
   --disable-maintainer-mode \
   --disable-dependency-tracking
```

**Comment by fgvanzee** [comment]
Thanks @nschloe . I'll work on this later today.

Thanks again for your comments, and for expressing interest in Debian packages! Please let us know if there is anything else that would be needed to facilitate your work.

**Comment by fgvanzee** [comment]
@nschloe I've pushed a commit (7e5648ca) to address this issue. Give it a try and let me know if you need further tweaks vis-a-vis `--libdir` and `--includedir`.

**Comment by nschloe** [comment]
Cool, let's close this.
