### ISSUE TITLE
how to change the kernel of haswell from 6x16/6x8 to 16x6/8x6

### ISSUE THREAD

**Issue by ShirleyGuo** [flame/blis#218]
I change the configuration from 6x16/6x8 to 16x6/8x6 in the file include/blis/blis.h before make install, but after make install, the file became unchanged, i.e.,  6x16/6x8. I don't know why. And the making the testsuite will throw error as follows:
Linking test_libblis.x against '.././lib/haswell/libblis.a -lm -lpthread -lrt'
.././lib/haswell/libblis.a(bli_cntx_init_haswell.o): In function `bli_cntx_init_haswell':
bli_cntx_init_haswell.c:(.text+0x8d): undefined reference to `bli_dgemm_haswell_asm_8x6'
bli_cntx_init_haswell.c:(.text+0x94): undefined reference to `bli_sgemm_haswell_asm_16x6'

**Comment by fgvanzee** [comment]
@ShirleyGuo It sounds like you are trying to change the kernels used by the `haswell` subconfiguration. Is this correct?

If so, you should first be aware that in the latest commits on the master branch, the `haswell` subconfiguration actually uses gemm microkernels in the `zen` kernel set. This is intentional and no cause for concern. The Haswell and Zen microarchitectures are similar enough that we can use the same kernel assembly code, and we happened to decide naming the kernels `zen` and letting `haswell` "borrow" those kernels. (We could have done the reverse, too, naming them `haswell` and letting `zen` borrow them.)

The next thing you should be aware of is that `blis.h` is a build product that is created just before compilation, used during compilation, and then installed by `make install`. (By the time you ran `make install`, the header had already been used to compile all of BLIS.) You should never change `blis.h` directly.

If you want to change the kernels that are used by a particular subconfiguration, first understand that this is a somewhat advanced/developer topic. (If you wish to proceed, that's okay; I just want to clarify that it's not meant to be 100% user friendly.) To change the gemm microkernel employed by BLIS, you need to modify the code that initializes the context for that microarchitecture. So for example, for Haswell, you should look inside `config/haswell/bli_cntx_init_haswell.c`. This is where you will adjust the function pointers to the desired kernels. But you'll need to take care of other things as well, such as making sure the kernel functions are properly prototyped. For a detailed explanation of this and other topics, please carefully read the [Configuration](https://github.com/flame/blis/wiki/ConfigurationHowTo) wiki.

**Comment by fgvanzee** [comment]
@ShirleyGuo Since you are trying to make a very specific change, I can offer some additional guidance.

As I point out above, the `haswell` subconfiguration actually uses `zen` microkernels in `kernels/zen/3`.

1. You need to make sure the microkernels you wish to use are prototyped in `kernels/zen/bli_kernels_zen.h`. We use macros for convenience, so it's just a matter of inserting the "base" name of the microkernels you wish to prototype. In this file, you can prototype any microkernels you find in `kernels/zen/3`.

2. You need to change `config/haswell/bli_cntx_init_haswell.c` so that your preferred microkernel is initialized into the context data structure for `haswell`. This should be intuitive based on the existing code. For more details, please read the [Configuration](https://github.com/flame/blis/wiki/ConfigurationHowTo) wiki.

3. Since you are changing the microkernel, you also need to update the appropriate register blocksizes (and possibly also cache blocksizes) associated with the microkernel. This is also done in `config/haswell/bli_cntx_init_haswell.c`.

After those changes, you configure and compile BLIS as you normally would.

**Comment by ShirleyGuo** [comment]
Thank you very.much. I have made it. 
by the way  how haswell borrows zen's kernels?

**Comment by ShirleyGuo** [comment]
Thank you very.much. I have made it. 
by the way  how haswell borrows zen's kernels?

**Comment by ShirleyGuo** [comment]
Thank you very.much. I have made it. 
by the way  how haswell borrows zen's kernels?

**Comment by fgvanzee** [comment]
@ShirleyGuo Glad you figured it out. 

> by the way how haswell borrows zen's kernels?

The kernel sets needed by each configuration are specified in the configuration registry, which is encoded in the `config_registry` file. The file has a very specific format. To interpret it properly, please see the [Configuration](https://github.com/flame/blis/wiki/ConfigurationHowTo) wiki.
