### ISSUE TITLE
adding extra build flags

### ISSUE THREAD

**Issue by loveshack** [flame/blis#223]
It would be useful if there was a hook in the build system to add extra CFLAGS and LDFLAGS on top of the optimization ones that get chosen.  When I looked before, doubtless without understanding the system properly, as far as I remember there wasn't an obvious place to edit the make fragments other then redefining the compile command; apologies if I missed something.

This came up in the review of the Fedora packaging <https://bugzilla.redhat.com/show_bug.cgi?id=1591910>, where there's a requirement for "security hardening" flags generally, even in numerical libraries. (That said, libxsmm uses its own set rather than distro-supplied ones, some of which apparently have a performance impact, so I'd be circumspect about using them all.) Another case might be if you wanted to build the generic implementation with architecture-specific flags.

**Comment by fgvanzee** [comment]
@loveshack I can add support for something like `EXTRA_CFLAGS` and `EXTRA_LDFLAGS`. I think that will be relatively straightforward. The semantics I envision are that you set the variables prior to running `configure`. After that, the values of those variables get embedded into `common.mk`. They will be used when compiling BLIS and linking the shared library. Furthermore, if you build the testsuite later, or any of the standalone test drivers, your `EXTRA_CFLAGS` and `EXTRA_LDFLAGS` will be used in those situations as well. Please let me know if this is not what you had in mind.

> Another case might be if you wanted to build the generic implementation with architecture-specific flags.

This case is already allowed, but you have to know what file to change (`config/generic/make_defs.mk`). So `EXTRA_CFLAGS` and `EXTRA_LDFLAGS` would probably be more intuitive there, as above.

**Comment by loveshack** [comment]
You wrote: 

> @loveshack I can add support for something like `EXTRA_CFLAGS` and
> `EXTRA_LDFLAGS`. I think that will be relatively straightforward. The
> semantics I envision are that you set the variables prior to running
> `configure`. After that, the values of those variables get embedded
> into `common.mk`. They will be used when compiling BLIS and linking
> the shared library. Furthermore, if you build the testsuite later, or
> any of the standalone test drivers, your `EXTRA_CFLAGS` and
> `EXTRA_LDFLAGS` will be used in those situations as well. Please let
> me know if this is not what you had in mind.

Yes, that's basically what I had in mind.  I guess they should go after
the normal ones in case they need to override anything (at one's own
risk).  Thanks!

**Comment by fgvanzee** [comment]
@loveshack I just realized we dealt with a similar issue in libflame, [issue 14](https://github.com/flame/libflame/issues/14).

Basically, before that issue, libflame had exactly this `EXTRA_CFLAGS` feature you've requested for BLIS. But the problem for @iotamudelta was that in FreeBSD's ports system, it's assumed that some basic `CFLAGS` can be set prior to building software X, and that those values be used in addition to whatever `CFLAGS` the build system for X would deem appropriate. The solution I crafted for him was to change the behavior of libflame's `configure` script so that by setting `CFLAGS` before building libflame, those flags would be prepended (instead of override) the values determined by libflame's build system. This obviated libflame's `EXTRA_CFLAGS`, with the only difference being that the "preset" CFLAGS would be prepended instead of being appended (as they would with `EXTRA_CFLAGS`).

So, before implementing `EXTRA_CFLAGS` for BLIS, I'd prefer that we all agree on a solution that will work for both you and @iotamudelta. 

@iotamudelta Is the problem of libflame's issue 14 not also a problem for BLIS? If not, can you tell us why? And if so, I assume you would prefer to see a solution for BLIS that is similar to that of libflame?

**Comment by loveshack** [comment]
You wrote: 

> Basically, before that issue, libflame had exactly this `EXTRA_CFLAGS`
> feature you've requested for BLIS. But the problem for @iotamudelta
> was that in FreeBSD's ports system, it's assumed that some basic
> `CFLAGS` can be set prior to building software X, and that those
> values be used in addition to whatever `CFLAGS` the build system for X
> would deem appropriate. The solution I crafted for him was to change
> the behavior of libflame's `configure` script so that by setting
> `CFLAGS` before building libflame, those flags would be prepended
> (instead of override) the values determined by libflame's build
> system. This obviated libflame's `EXTRA_CFLAGS`, with the only
> difference being that the "preset" CFLAGS would be prepended instead
> of being appended (as they would with `EXTRA_CFLAGS`).

That would be fine, and actually preferable, now I wake up and think.
It's what happens for a vanilla build of an autotools-configured
package, and you want the internally-set flags to override
externally-defined ones which include -O2 -mtune=generic in Fedora's
case.  I wouldn't worry about an EXTRA_ variable unless someone needs
it, or it's trivial to add.

I don't know ports, but I guess it works similarly to rpm in this
respect, and the hook should be of general use.  (It needs LDFLAGS
treating similarly to CFLAGS, in case that gets forgotten.)
Thanks!

**Comment by fgvanzee** [comment]
@iotamudelta Yes, sounds like you followed along. Sorry that I was not more clear in catching you up on this issue. (It also occurred to me that if you wanted the new CFLAGS behavior in libflame, per issue 14, you would probably want it in BLIS as well.)

@loveshack Great. Glad this works for your purposes and, as you said, is even preferable to the `EXTRA_CFLAGS` behavior.

It turns out that @devinamatthews was another vote in favor of the preset CFLAGS awareness; he informed me that this is more-or-less standard behavior in many other projects (perhaps it's an autotools thing, or maybe just convention).

**Comment by fgvanzee** [comment]
@loveshack @iotamudelta I've implemented this feature in 884175d. Notice that it is available for both `CFLAGS` and `LDFLAGS`. (I later made a small update in f986396.)

Please try it out and let me know if anything looks off.
