### ISSUE TITLE
``configure`` should default to the ``auto`` configuration

### ISSUE THREAD

**Issue by poulson** [flame/blis#25]
It seems strange for `configure` not to default to the `auto` configuration. It took a bit of digging for me to find that this was supported. Why not attempt the auto-detection instead of failing?

**Comment by fgvanzee** [comment]
A few comments:
* In the beginning, the `reference` configuration was the default when `configure` was run with no unparsed arguments. This was later changed so that the developer had firm knowledge of which configuration he was using
* The `auto` option to `configure` is very new.
* I am in the early planning stages of an effort to retrofit runtime kernel and blocksize selection via auto-detected CPU features. This will affect the build system and configure-time approach as well. Everything is in flux, so please just sit tight for now.
* Recall that I am recovering from an RSI. Read: Please be patient with the crippled guy.

Thanks for your feedback.

**Comment by poulson** [comment]
Thanks Field. It no longer effects me since I will have Elemental specify ``auto`` by default, but it might make potential users' life easier.

**Comment by fgvanzee** [comment]
I agree that it would make an end-user's life easier. But until recently, we were really only targeting developers who usually were in the business of tightly controlling their configuration parameters, not end-users who wanted to configure, build, and then walk away (until a new version was needed).

As far as I am concerned, the current build system is just a temporary hack. There may not be much left of it by the time I am done, or it may only require small tweaks. I'm not sure yet. But I will take your advice to heart. As we enter this new phase, in which user-friendliness is targeted, I agree that  default behavior of `configure` should be to auto-detect.

**Comment by jeffhammond** [comment]
Closing as "won't fix", based upon discussion here.
