### ISSUE TITLE
Configuring Python

### ISSUE THREAD

**Issue by loveshack** [flame/blis#268]
Could configure take, say, PYTHON from the environment and substitute "/usr/bin/env python" with that in flatten-headers.py?
That would avoid having to maintain a patch for packaging; for instance /usr/bin/python3 is required in Fedora.

**Comment by fgvanzee** [comment]
Hopefully this is not a dumb question, but is `PYTHON` a standardized environment variable for the current python interpreter? 

Also, is python3 ubiquitous enough yet that we can simply assume it is always present?

**Comment by isuruf** [comment]
> Hopefully this is not a dumb question, but is PYTHON a standardized environment variable for the current python interpreter?

It's not widely used, but if it is set, you can use it.

> Could configure take, say, PYTHON from the environment and substitute "/usr/bin/env python" with that in flatten-headers.py?

shebang line has a limit and if the PYTHON env variable value length is greater than 128 this would fail.

**Comment by loveshack** [comment]
You wrote: 

> Hopefully this is not a dumb question, but is `PYTHON` a standardized
> environment variable for the current python interpreter?

Yes, at least in the GNU build system.

> Also, is python3 ubiquitous enough yet that we can simply assume it is
> always present?

I don't know, but python2 is on its way out, which is why 3 is being
required for packaging, but I wasn't suggesting changing it.  I'd lave
the default as-is, and only override it if PYTHON is defined.  I think
it just needs something like

  [ -n "$PYTHON" ] && sed -i -e "s@/usr/bin/env python@$PYTHON@"

and the doc.

**Comment by loveshack** [comment]
> shebang line has a limit and if the PYTHON env variable value length
> is greater than 128 this would fail.

It won't be, but I could still use env if it was in some crazy
distribution.

**Comment by fgvanzee** [comment]
> but I wasn't suggesting changing it. 

But I was! :) I'd rather statically assign it to something that works everywhere, but it appears I'm not so lucky at this point in time. Maybe I'll check back in five years when python2 is more dead than today? lol

> `[ -n "$PYTHON" ] && sed -i -e "s@/usr/bin/env python@$PYTHON@"`

Would `PYTHON` ever be set to, for example, `/usr/bin/env python3`? If so, we would need to make the matching expression stronger (matching the end of line as well?) since repeated invocations of `configure` would result in  `/usr/bin/env python3`, and then  `/usr/bin/env python33`, etc. But if not, i'm more or less on board with this.

@devinamatthews See any problems with Dave's suggestion?

**Comment by isuruf** [comment]
@fgvanzee, my suggestion is to change the line https://github.com/flame/blis/blob/667d3929ee20e94849b4e25b693b4037b7e3f350/common.mk#L441 to `FLATTEN_H := $(PYTHON) $(DIST_PATH)/build/flatten-headers.py` which should work if `$PYTHON` is set or not

**Comment by fgvanzee** [comment]
Oooh, I like @isuruf's suggestion. Changing the script at configure-time was always kind of icky. Will this suffice for your purposes, @loveshack?

**Comment by loveshack** [comment]
You wrote: 

>> but I wasn't suggesting changing it. 
>
> But I was! :) I'd rather statically assign it to something that works
> everywhere, but it appears I'm not so lucky at this point in
> time. Maybe I'll check back in five years when python2 is more dead
> than today? lol

I expect you can rely on python3 being available on any
currently-supported GNU/Linux distribution, at least.  I don't know
whether you can rely on a "python3", as opposed to "python3.6", for
instance.  It's a mess.

>> `[ -n "$PYTHON" ] && sed -i -e "s@/usr/bin/env python@$PYTHON@"`
>
> Would `PYTHON` ever be set to, for example, `/usr/bin/env python3`? If
> so, we would need to make the matching expression stronger (matching
> the end of line as well?) since repeated invocations of `configure`
> would result in `/usr/bin/env python3`, and then `/usr/bin/env
> python33`,

Oops, yes, it should have been anchored.

**Comment by loveshack** [comment]
You wrote: 

> Oooh, I like @isuruf's suggestion. Changing the script at
> configure-time was always kind of icky. Will this suffice for your
> purposes, @loveshack?

Yes, you normally transform ".in" files.

It will work.  However, given a configure script, PYTHON would
conventionally be relevant at configure time, consistent with CFLAGS,
rather than having to use parts of the environment for configure and for
make.

**Comment by fgvanzee** [comment]
@loveshack Okay, great. I'll add this to my near-term to-do list.

**Comment by loveshack** [comment]
> Okay, it's ready to try out in [5a1e461](https://github.com/flame/blis/commit/5a1e461ffe09ed200ee2fc7aafccf6dd7e8c0080) on the `master` branch. Thanks Isuru for your help on this.
> 
> Let me know if this works for you, Dave.

It will avoid the need for a patch, but I think it should be done in configure, as I said previously.
Apologies for the late reply.

**Comment by loveshack** [comment]
I should have said it needs some doc too.

**Comment by fgvanzee** [comment]
@loveshack The PYTHON variable is now mentioned in the output to `configure --help` as an observed environment variable. The bottom of the output reads:
```
 Environment Variables:
 
   CC            Specifies the C compiler to use.
   RANLIB        Specifies the ranlib executable to use.
   AR            Specifies the archiver to use.
   CFLAGS        Specifies additional compiler flags to use (prepended).
   LDFLAGS       Specifies additional linker flags to use (prepended).
   LIBPTHREAD    Pthreads library to use.
   PYTHON        Specifies the python interpreter to use.
 
   Environment variables may also be specified as command line
   options, e.g.:
 
     ./configure [options] CC=gcc haswell
 
   Note that not all compilers are compatible with a given
   configuration.
```
Let me know if you feel this is inadequate.

**Comment by cdluminate** [comment]
Any update on this? Fixing this issue also helps me get rid of this patch https://salsa.debian.org/science-team/blis/blob/master/debian/patches/build-use-py3.patch

**Comment by cdluminate** [comment]
> @loveshack The PYTHON variable is now mentioned in the output to `configure --help` as an observed environment variable. The bottom of the output reads:
> 
> ```
>  Environment Variables:
>  
>    CC            Specifies the C compiler to use.
>    RANLIB        Specifies the ranlib executable to use.
>    AR            Specifies the archiver to use.
>    CFLAGS        Specifies additional compiler flags to use (prepended).
>    LDFLAGS       Specifies additional linker flags to use (prepended).
>    LIBPTHREAD    Pthreads library to use.
>    PYTHON        Specifies the python interpreter to use.
>  
>    Environment variables may also be specified as command line
>    options, e.g.:
>  
>      ./configure [options] CC=gcc haswell
>  
>    Note that not all compilers are compatible with a given
>    configuration.
> ```
> 
> Let me know if you feel this is inadequate.

This looks good to me. Thanks!

**Comment by loveshack** [comment]
I thought I'd commented on this, but obviously not.
configure doesn't actually do anything with PYTHON other than reject
various versions for some reason.  You need to supply it to make as
well.  I just exported it in the spec file.

The installation doc just says python 2.7+ is required, but 3.1-3.4 are
rejected.  I've successfully used 2.6 (RHEL6) and 3.4, and the code
doesn't seem to have changed since then, so I suspect 2.6+ is OK.
What's the reason for rejecting those versions?

**Comment by isuruf** [comment]
python 2.6 doesn't work according to https://github.com/flame/blis/issues/258#issuecomment-425270173

**Comment by fgvanzee** [comment]
@loveshack Yes, as Isuru points out, we've run into trouble with older 2.x pythons. Version 2.7 seems to be needed if you're using Python 2. If you're using Python 3, I seem to recall 3.5 or newer being needed for some reason, possibly involving the `re` module. And for the record, the only reason python is needed is for the `flatten-headers.py` script, which, as part of the build system, recursively inlines all C header files in BLIS into the `blis.h` that is output to `include/<config>/blis.h`. (It is this header that is compiled against and, if `make install` is run, installed.)

**Comment by loveshack** [comment]
Apologies, yes, it doesn't work with python2.6; I thought I'd tested
that recently and had obviously forgotten the status.  Suffering from
something flu-like might be an excuse.

However, it definitely does work with 3.4, which is the python3 version
in RHEL6 and 7, and is the earliest I can check trivially.  BLIS 0.5
broke my rpm packaging for those, and I'll need to modify the configure
check.  (Sure, about what it's used for, though I haven't figured out
why it needs a python program.)

**Comment by fgvanzee** [comment]
> However, it definitely does work with 3.4, which is the python3 version in RHEL6 and 7, and is the earliest I can check trivially.

Apparently I didn't put forth a whole lot of effort in trying to pin down the precise minimum version of python3 needed, probably because I assumed that newer versions of python3 were commonplace. If you are fairly certain that the latest commits on `master` build without issue on python 3.4, I can adjust the python version blacklisting and/or attempt to identify the true version crossover.

> (Sure, about what it's used for, though I haven't figured out why it needs a python program.)

BLIS doesn't *need* python; bash will work, too. The reason to use python is speed. The python script I described previously makes heave use of search-and-replace and also happens to be file-intensive. Executing the equivalent `sed`-based bash script seems to perform 4-8x more slowly than the python script we have now. (The bash script actually came first, and then inspired the python script because I was unsatisfied with the script's runtime.)

**Comment by fgvanzee** [comment]
It is just occurring to me that, in principle, the build system could execute the bash variant of `flatten-headers` if the python version is found to be lacking (e.g. 2.6.x). However, I hesitate on this because it would require me to maintain two versions of the same (somewhat sophisticated) script going forward.

Dave: how big of an inconvenience is it for a package to require python 2.7 or newer? (Let's assume for a moment that `configure` is currently being overly conservative and unnecessarily rejecting python3 prior to 3.4/3.5.)

**Comment by loveshack** [comment]
You wrote: 

> Apparently I didn't put forth a whole lot of effort in trying to pin
> down the precise minimum version of python3 needed, probably because I
> assumed that newer versions of python3 were commonplace. If you are
> fairly certain that the latest commits on `master` build without issue
> on python 3.4, I can adjust the python version blacklisting and/or
> attempt to identify the true version crossover.

The rpms for EPEL7 were built with 3.4.  The build log for that is at
<https://kojipkgs.fedoraproject.org//packages/blis/0.4.1/2.el7/data/logs/x86_64/build.log>.
I suspect something older will also work, but 3.4 is probably good
enough generally unless SLES has something older.

> BLIS doesn't *need* python; bash will work, too. The reason to use
> python is speed.

I'd expect to do #include-processing with cpp, but maybe that's not
sufficiently portable.  Anyhow, allowing python 3.4 is good enough.

**Comment by loveshack** [comment]
You wrote: 

> Dave: how big of an inconvenience is it for a package to require
> python 2.7 or newer? (Let's assume for a moment that `configure` is
> currently being overly conservative and unnecessarily rejecting
> python3 prior to 3.4/3.5.)

That's fine from the point of view of Fedora packages, at least, which
currently just require /usr/bin/python3, i.e. v3.4 on RHEL6 and 7.  I'd
expect (RH)EL7 to be the most common HPC platform these days, or at
least well up there.

By the way, I can only see python2.6 on the Cray I can access
(apparently CLE release 11), but I assume any such system will have at
least one (:-/) environment module for python3.

**Comment by fgvanzee** [comment]
> I suspect something older will also work, but 3.4 is probably good enough generally unless SLES has something older.

Okay, I'll relax the version blacklisting for python3 later today to allow 3.4 and newer.

> I'd expect to do #include-processing with cpp, but maybe that's not sufficiently portable.

You are absolutely correct that using the C preprocessor would work, and it would be plenty portable, too. Indeed, that's how we originally did things with BLIS: `blis.h` would recursively `#include` hundreds of smaller header files scattered throughout the source tree. The problem with this was twofold.

First, managing/installing hundreds of header files at install-time, while very doable, was less than ideal from a package management and distribution standpoint. This motivated me to investigate the idea of a `flatten-header`, since I couldn't find the right set of flags to `gcc` (similar to `-E`) that would cause it to output what I wanted. Once I began working with the monolithic/flattened headers, I realized that there was a second benefit: faster compilation time. Turns out that while the C preprocessor is very efficient about `#include`ing files, it does measurably increase the total preprocessing/compilation time when it must go through those motions for 500 headers every time a source file is compiled.

**Comment by fgvanzee** [comment]
Commit daacfe68 now allows running `configure` with python 3.4. Thanks for your help, Dave.

**Comment by loveshack** [comment]
You wrote: 
> This motivated me to investigate the idea of
> a `flatten-header`, since I couldn't find the right set of flags to
> `gcc` (similar to `-E`) that would cause it to output what I
> wanted.

I'm surprised at that, but it would probably be gcc-specific, so
presumably not portable enough I realized.

Thanks for relaxing the version check.

**Comment by fgvanzee** [comment]
> I'm surprised at that

I was too. My script, functionally, is probably useful to many others out there.

**Comment by fgvanzee** [comment]
@loveshack Can we consider this issue closed? Let me know if there are outstanding items yet to be addressed.

**Comment by loveshack** [comment]
Yes, you can close it.
