### ISSUE TITLE
Custom packing kernels and edge cases

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#282]
Hot on the heels of #281, I have found that even when one goes to the trouble of writing custom packing kernels, in the case that `m != MR` or `n != NR` then the reference kernels are used. In my case, the packing kernel has to pack two rows (of the k loop) at once in an interleaved fashion. Thus, the edge cases come out incorrect.

It would be nice to be able to use a custom packing kernel in all cases.

**Comment by fgvanzee** [comment]
Devin, could you clarify some things for me? It's not clear what you mean by `m != MR or n != NR`. That is, what are `m` and `n`? 

Furthermore, it's not clear to me what you mean by "pack two rows (of the k loop)" means, since a micropanel can be row- or column-oriented, with micro-columns or micro-rows, respectively.

**Comment by devinamatthews** [comment]
>  It's not clear what you mean by m != MR or n != NR. That is, what are m and n?

I mean the micropanels at the end of the full panels that are zero-padded.

>Furthermore, it's not clear to me what you mean by "pack two rows (of the k loop)" means, since a micropanel can be row- or column-oriented, with micro-columns or micro-rows, respectively.

The microkernel I wrote computes two iterations of the k loop at a time, and hence needs a different packing format. From the code:

```C
//
// A (in memory): |a00 a01           a10 a11           a20 a21        |
//
// A (registers): (a00 a01 a00 a01) (a10 a11 a10 a11) (a20 a21 a20 a21)
//
// B (in memory): |b00 b10 b02 b12   b01 b11 b03 b13  ...
//
// B (registers): (b00 b10 b02 b12) (b01 b11 b03 b13) ...
//
// C (registers, needs horizontal add):
//
//   ymm4-6:   (c00 c00 c02 c02) (c10 c10 c12 c12) (c20 c20 c22 c22)
//   ymm7-9:   (c01 c01 c03 c03) (c11 c11 c13 c13) (c21 c21 c23 c23)
//   ymm10-12: (c04 c04 c06 c06) (c14 c14 c16 c16) (c24 c24 c26 c26)
//   ymm13-15: (c05 c05 c07 c07) (c15 c15 c17 c17) (c25 c25 c27 c27)
//
```

e.g. A is loaded with `vbroadcast128f`.

**Comment by devinamatthews** [comment]
Note that this type of format is also needed on KNM.

**Comment by fgvanzee** [comment]
@devinamatthews What are your register blocksizes in the above example?

**Comment by devinamatthews** [comment]
3x8

**Comment by fgvanzee** [comment]
I think I understand. Each micro-column of A has been replaced by a tiny micropanel whose "NR" is 2, and each micro-row of B has been replaced by a tiny micropanel whose "MR" is 2.

Also, you made a good point that there is currently no way to specify a packm kernel for the edge cases where the panel dimension is less than the register blocksizes.

Let me think about this.

**Comment by devinamatthews** [comment]
FYI the way I have it implemented in TBLIS, the packing kernel specified by the configuration (whether a custom one or the reference) is responsible for zero-padding edge cases. This makes the kernels slightly more complicated but lets you do anything you want during packing.

**Comment by fgvanzee** [comment]
Oh, interesting. Thanks for that suggestion.

**Comment by fgvanzee** [comment]
Okay, I agree in principle with the idea of moving the responsibility of zero-filling to the `packm` kernel. However, this is something I want to do very carefully to make sure that it doesn't unintentionally break things related to hermitian/symmetric/triangular packing. (Translation: It may take some time.)

**Comment by devinamatthews** [comment]
That is good enough as a near-term target.

**Comment by fgvanzee** [comment]
@devinamatthews I started work on this issue. In the middle of the change for "native" (not 1m) packm kernels, I stopped and intentionally introduced what I thought was a bug: I disabled all zero-setting, including in the newly modified reference packm kernels, *and* I used `memset()` in `bli_malloc_*()` to set everything to a non-zero value before returning the pointer. The testsuite for `gemm` passed for all problem sizes from 1 to 300. It was then that I realized that this was expected, since the "bad" elements--the ones that I was temporarily *not* setting to zero--correspond to values of C that do not exist, and thus are not stored back to C.

So, my question is, can you think of a reason why reference packm kernels (or any packm kernels) should go to the trouble of setting the edge region of edge-case micropanels to zero? I can't figure out if I was being overly conservative when initially writing that part of BLIS, or if I had some specific use case in mind for why setting to zero was required.

**Comment by fgvanzee** [comment]
A thought: Is it possible that computing with `NaN` and/or `Inf` would slow down the microkernel?

**Comment by fgvanzee** [comment]
@devinamatthews FWIW, I realized why it was so important to zero out the boundary regions in edge case micropanels (aside from possibly causing a slowdown from computing with `NaN`): `trsm` needs those edge case regions to be zero, especially in the triangular blocks where the diagonal is extended and set to 1.

I'm almost done preparing the commit. (It was relatively disruptive given the number of affected `packm`-related functions that needed to be touched. But I agree that this change was the right thing to do.)

**Comment by fgvanzee** [comment]
@devinamatthews Give f808d82 a try. See any of the reference kernels, or the commit log, for the new kernel API. Let me know if you have any questions.

**Comment by fgvanzee** [comment]
@devinamatthews I'm going to close this issue, since I'm pretty sure it's taken care of now. But please re-open if you have any further concerns.
