### ISSUE TITLE
docs/HardwareSupport.md needs updating

### ISSUE THREAD

**Issue by loveshack** [flame/blis#290]
The list of documented targets differs from the current output of configure -c.

**Comment by fgvanzee** [comment]
Thanks for pointing this out, Dave.

I've taken a look at it. In some cases, the configurations really are missing, such as with `power7` and `generic`. But in other cases, the differences don't amount to much. For example, we aren't trying to document the `intel64` and `amd64` configuration families in `HardwareSupport.md` (though maybe we should?) since they are bundles of configurations, rather than corresponding to distinct hardware types.

We can leave this issue open for now. I'll fix/clean up the missing `power7` entry once we add new power9 kernels, which we contributed by IBM and waiting for integration. In the meantime, you and others can comment on the configuration family discrepancy if you care to.

**Comment by fgvanzee** [comment]
> In case it's not clear, the doc has "power7" -- I don't know if you mean to revive that 

Yes, I meant power9. :) As you point out, we also have power7.

> It would be clearer to separate cortex a9 and a15 in the table, like the x86_64 micro-architectures. 

I can do that.

> Also, it would be helpful to say which of the cortexa5x is generic enough for all aarch64 -- someone said, but I've forgotten -- and if either a9 or a15 will do for all armv7hl (in distribution labelling).

Unfortunately, this is beyond my expertise. Someone like @figual or @dnparikh will have to help with that.

**Comment by devinamatthews** [comment]
I think most of this is fixed/moot now. Re:

> Also, it would be helpful to say which of
the cortexa5x is generic enough for all aarch64 -- someone said, but
I've forgotten -- and if either a9 or a15 will do for all armv7hl (in
distribution labelling).

I don't think it is the intent of that particular document to describe the higher-level meta-configurations. That *should* be elsewhere in the build documentation.
