### ISSUE TITLE
noise from omp simd pragmas

### ISSUE THREAD

**Issue by loveshack** [flame/blis#297]
It's not very important, but if support for the simd pragma isn't available (e.g. native GCC on RHEL7), there can be quite a lot of noise from unknown pragma warnings during the build.

I may not be worth the effort, but presumably that could be avoided by replacing _Pragma() with a configured macro (which I assumed was the reason to use _Pragma rather than #pragma).

**Comment by fgvanzee** [comment]
Thanks for pointing this out, Dave. I'll let @devinamatthews comment on how we might best pacify the compiler. (The solution you suggest seems simple enough, though we would need to write a `configure` test for it.) I assume these are warnings and not errors? Otherwise you'd probably indicate that this issue was more than "not very important." :)

As for why we used `_Pragma()` instead of `#pragma`, the reason is as follows: reference kernels in BLIS are defined via so-called templatizing macros, and to the best of my knowledge `#pragma` (along with other preprocessor macros) cannot be used in the *definition* of a macro. Using `_Pragma()` gets around this limitation.

**Comment by devinamatthews** [comment]
@fgvanzee there should already be a `configure` test for it--if `-fopenmp-simd` works then turn the pragma on, else turn it off.

**Comment by fgvanzee** [comment]
@devinamatthews Ha, you're right! I forgot that we have a test. It currently does nothing aside from echo the observed presence of absence of support for `#pragma omp simd`. I'll add the appropriate macro-disablage.

**Comment by devinamatthews** [comment]
@fgvanzee Does it add `-fopenmp-simd` in the Makefile? That is an important step because no compiler recognized the pragma by default...

**Comment by fgvanzee** [comment]
Yes, it does that. So not nothing. Just nothing vis-a-vis cpp macro definitions.

**Comment by loveshack** [comment]
On 12 February 2019 17:16:54 GMT+00:00, "Field G. Van Zee" <notifications@github.com> wrote:
>Thanks for pointing this out, Dave. I'll let @devinamatthews comment on
>how we might best pacify the compiler.

You can use -Wno-pragmas (?) with gcc, at least. Yes, it's just warnings.

>As for why we used `_Pragma()` instead of `#pragma`, the reason is as
>follows: reference kernels in BLIS are defined via so-called
>templatizing macros, and to the best of my knowledge `#pragma` (along
>with other preprocessor macros) cannot be used in the *definition* of a
>macro. 

Er, yes; brain not engaged, even with code in front of me.

Actually I'm not convinced by the pragmas anyway.
Info on that tomorrow, probably.


-- 
Sent from a pocket telegraph machine; excuse the result.

**Comment by fgvanzee** [comment]
Since we don't want any disabling of the `_Pragma` for the reference kernels to affect potential use for OpenMP-based multithreading, I'm going to have to disable the `#pragma` directives just for reference kernels, which means modifying the compiler flags for only those files. (I could change the multithreading `_Pragma` to a `#pragma` since it's not in a macro definition, and then leave the reference kernel occurrences as `_Pragma`, which can be globally preprocessed away, but that seems hackish and like something that could bite me in the future.)

**Comment by devinamatthews** [comment]
```C
#if HAS_OMP_SIMD
#define OMP_SIMD _Pragma("omp simd")
#else 
#define OMP_SIMD
#endif 
```
right?

**Comment by jeffhammond** [comment]
+1 to `_Pragma`.  See https://github.com/jeffhammond/nwchem-tce-triples-kernels/blob/master/src/pragma_vendor.h if you want to enable non-OpenMP SIMD flags.

**Comment by fgvanzee** [comment]
@devinamatthews @jeffhammond Thanks for offering those suggestions. It seems like you are suggesting to:
1. Adopt a header file in BLIS similar to the `pragma_vendor.h` Jeff links to above.
2. Change all occurrences of `_Pragma( "omp simd" )` in BLIS's reference kernels to instead use `OMP_SIMD` or whatever macro is defined in the `pragma_vendor.h` equivalent in BLIS.

And this would mean we could take care of this whole issue within header rather than by modifying compiler options of the affected files.

**Comment by devinamatthews** [comment]
Yes. Basically I almost always try to put any `_Pragma` behind a macro that can be toggled.

**Comment by fgvanzee** [comment]
Okay, I'll start working on this. What kind of attribution would be appropriate for basing the code on the `pragma_header.h` in NWChem?

**Comment by fgvanzee** [comment]
@jeffhammond I can't find any evidence that `#pragma gcc simd` (or `#pragma GCC simd`) is a thing. Do you have any background on this?

**Comment by fgvanzee** [comment]
Perhaps the `#pragma gcc simd` syntax has been deprecated in favor of `#pragma omp simd`? These [gcc docs](https://gcc.gnu.org/onlinedocs/gcc/Loop-Specific-Pragmas.html#Loop-Specific-Pragmas) only list `ivdep` and `unroll` as valid pragmas.

**Comment by fgvanzee** [comment]
@loveshack I've committed 6b83273, which should prevent compiler warnings when `-fopenmp-simd` is unavailable.

**Comment by loveshack** [comment]
> @jeffhammond I can't find any evidence that `#pragma gcc simd` (or
> `#pragma GCC simd`) is a thing. 

It isn't, as you can see with -Wunknown-pragmas (at least in GCC 8).

"GCC ivdep" is in GCC 6 and "GCC unroll" is in 8 (maybe 7?).  (I've seen
ivdep recommended where restrict should have been used instead.)

**Comment by loveshack** [comment]
> And this would mean we could take care of this whole issue within
> header rather than by modifying compiler options of the affected
> files.

I don't see how.  You have to add -fopenmp-simd, or not add it, so you
can define the macro null as nothing when not using -fopenmp-simd.

Anyhow, the best thing seems to be not to use the pragma, at least with
GCC, and I probably shouldn't have commented on the noise.  Data anon.

**Comment by fgvanzee** [comment]
> I don't see how. You have to add -fopenmp-simd, or not add it, so you can define the macro null as nothing when not using -fopenmp-simd.

Perhaps I misspoke. As you point out, we were already affecting compiler flags by including or withholding `-fopenmp-simd`. In my comment, was referring to potentially disabling `_Pragma("omp simd")` via the command line, e.g. `-D'_Pragma(s)='` to disable altogether. Indeed, this is what my original commit draft looked like. But then @jeffhammond and @devinamatthews convinced me to generalize it further into the final solution that I ended up with, which does the same thing as that initial draft but without needing to change the compiler options (beyond including or withholding `-fopenmp-simd`). The logic of disabling or enabling the `_Pragma("omp simd")` for reference kernels is now handled by controlling the behavior of an intermediate macro, `PRAGMA_SIMD`, which is either defined to be `_Pragma("omp simd")` or defined away to nothing.

**Comment by jeffhammond** [comment]
@fgvanzee `#pragma GCC simd` is probably an error.  It seems to be `#pragma GCC ivdep` instead (https://gcc.gnu.org/onlinedocs/gcc/Loop-Specific-Pragmas.html#Loop-Specific-Pragmas) but since I only use GCC that supports `#pragma omp simd`, I've never bothered to test it.

**Comment by jeffhammond** [comment]
@fgvanzee Attribution not required on that header.  I wrote that code while employed by Argonne and it was not extracted from NWChem.

**Comment by fgvanzee** [comment]
@jeffhammond Thanks Jeff. (Before you responded, I had included a comment and link to the header you provided. I'll leave that in for the time being.)

**Comment by devinamatthews** [comment]
It looks like this is fixed albeit without recent confirmation.
