### ISSUE TITLE
Poor performance in MUMPS/BLIS compared to OpenBLAS

### ISSUE THREAD

**Issue by cosstas** [flame/blis#308]
This is rather a topic for discussion than an actual issue.
The scientific code I am employing is using MUMPS solver ([http://mumps.enseeiht.fr/](url)), which requires LAPACK, ScaLAPACK, MPI and of course a BLAS library. When I got my hands on an AMD EPYC machine, I thought to give BLIS a try since it is the only library (to the best of my knowledge) that has zen arch specific optimizations.
However, the initial test showed a significant slow-down (30-40% in total code execution, probably greater for the MUMPS solving step, but this varies depending on model size/setup).
My setup is rather 'exotic', i.e Windows/MS-MPI and used MSYS2 to build all dependencies. I followed the same procedure in building ScaLAPACK and MUMPS and similar parameters in building BLAS/BLIS, most notably. no threading since there is one thread per MPI process. Of course, with BLIS I had to build LAPACK separately, since OpenBLAS includes it.
Troubleshooting the issue is beyond my abilities (and time restrictions) so I turn to you (the developers) for advice.
I can provide any detail regarding my build setup if it would help.

**Comment by devinamatthews** [comment]
Do you know which LAPACK/BLAS operations the program spends most of its time?

**Comment by fgvanzee** [comment]
@cosstas Some relevant questions:
1. "Slowdown" relative to what? (OpenBLAS?)
2. What distribution of BLIS are you using? Ours, or AMD's?
3. Please describe your machine. A model number is a good start.
4. How are you configuring BLIS?

It is probably worthwhile to benchmark the individual operation(s), which @devinamatthews asked about, rather than try to infer what is going on from the "top line" application performance. If your application uses `gemm` mostly, and we can identify the slowdown when measuring `gemm`, then that is a simpler laboratory in which to experiment than via your MUMPS solver.

**Comment by rvdg** [comment]
MUMPS is a sparse direct solver where inherently one starts with a lot of parallelism of many small subproblems and eventually you end up with a few very large subproblems.  This is the problem that Kyungjoo made progress on in his dissertation, but using his own sparse direct solver.

If you pick where you get what parallelism wrong, then this would greatly impact performance.  It is a delicate balancing act.  The fact that it involves LAPACK and ScaLAPACK further complicates things, because of the number of tuning parameters that introduces.

So, here is a situation where switching to a new BLAS library without understanding what default choices were made can greatly affect performance.  It will take some investigating on the part of the MUMPS user.  It is a MUMPS developer who really should provide guidance.

If Kyungjoo is on this list, he may be able to provide insight.

Robert

**Comment by kyungjoo-kim** [comment]
@cosstas  Hi. Some clarification might be needed as @fgvanzee mentioned. 

A few comments are
1. As you use a single thread per mpi node, make sure that you use sequential blis library or set omp parameter to use a single thread. @fgvanzee Do we have any additional blis environment variable to restrict the library to the sequential mode ?

2. You may also want to identify where the slowness comes from. You first need to measure the MUMPS performance. I don't think that it is never a good idea to guess the MUMPS performance by just taking total execution time of your code. By controlling MUMPS parameters you can print out everything e.g., number of rows, symmetry of the problem, double or complex, biggest frontal matrix size, memory usage, giga flop/s. These information would help to characterize your system of equations. 

3. MUMPS has the numeric phase (factorization) and the solve phase (forward and backward triangular solve). Would you identify where the slowness comes from ? If you do solve with different right hand side many times or many right hand sides, it could be from the solve phase. If you need to factorize the matrix for every time iteration, the slowness is probably from the factorization. 

   case 1) Factorization is the trouble maker. Would you perform a small benchmark of GEMM and TRSM varying the problem sizes from 100 to 5000 with every 100 and make sure if you can reproduce what BLIS reports in the paper (I mean the "efficiency" compared to theoretical peak of your machine) ? The range of problem sizes is typically used for frontal matrix computation.

  case 2) Solve is the trouble maker. If this is the problem, that means that you either solves many right hand side or perform the solve phase many many times. Either way, MUMPS would use level 2 BLAS functions and I am not sure how much room for improvement or BLIS can help in this case. As the level2 operations mostly bounded by the bandwidth, I don't think that the 30% difference is due to the level2 functions. Anyway, @fgvanzee do we ever report level 2 BLAS comparison in a paper ? 

  case 3) You might use BLAS and LAPACK some other places and it causes the slowness. In this case, let us know which functions you use.

**Comment by fgvanzee** [comment]
> @fgvanzee Do we have any additional blis environment variable to restrict the library to the sequential mode ?

BLIS runs sequentially by default, even if it is built with multithreading enabled. Multithreaded behavior is only observed if one of {`BLIS_NUM_THREADS`, `OMP_NUM_THREADS`} is set to something more than 1 (and multithreading is enabled at configure-time).

> Anyway, @fgvanzee do we ever report level 2 BLAS comparison in a paper ?

We don't have any level-2 operation performance results on hand for recent architectures like Haswell through Skylake. However, *for the real domain*, level-2 performance shouldn't be too bad, even if it is a bit lower than MKL/OpenBLAS.

**Comment by cosstas** [comment]
First of all, thank you all for your interest. It was getting late here and couldn't provide more information at the time. 
@devinamatthews 
>     Do you know which LAPACK/BLAS operations the program spends most of its time?
Unfortunately, I don't have the necessary programming background to answer that. I didn't know what a 'makefile' was until I set out to compile MUMPS in Windows.
@fgvanzee 
>     1. "Slowdown" relative to what? (OpenBLAS?)
Yes, by measuring the total execution time of the code. I know it provides little insight, but its an indicator something doesn't work. After all, that is the aim, to finish our work sooner. :)
>     2. What distribution of BLIS are you using? Ours, or AMD's?
After your comment [here](https://github.com/flame/blis/pull/194#issuecomment-481319893), I opted for the latest flame/BLIS release (0.5.2).
>     3. Please describe your machine. A model number is a good start.
My workstation has an AMD EPYC 7401P 24-core single socket CPU, on a Supermicro H11SSL MB with 64GB RAM.
>     4. How are you configuring BLIS?
As simple as that:
`./configure --disable-shared zen`
>    5. Do you know what problem sizes are being executed?
I don't think I can answer that, but I am attaching the code's subroutines that call MUMPS:
[pre4_mumps.F.txt](https://github.com/flame/blis/files/3067262/pre4_mumps.F.txt)
[solve_mumps_par.F.txt](https://github.com/flame/blis/files/3067263/solve_mumps_par.F.txt)

The code that I am using is called ARTEMIS and is part of the opentelemac suite [http://www.opentelemac.org/](http://www.opentelemac.org/). The mesh is partitioned into smaller sub-domains, one for each MPI process.
@kyungjoo-kim 
I get the gist but I don't have the skill to follow up. It requires far greater involvement than I can spare at this point. Will try though if I get the chance. I am planning to run the builtin ScaLAPACK/ MUMPS tests for each setup and see how they compare.

**Comment by kyungjoo-kim** [comment]
@cosstas 

Looking at the solve_mumps_par.F, you use job id 6 which means that you always factorize and solve once. Your RHS is a single vector. 

A simple change to show the statistics would be changing line 74 and 75. 
```
!! MUMPS_PAR%ICNTL(3) = -1 
!! MUMPS_PAR%ICNTL(4) = 0
```
By commenting these two lines, MUMPS uses default values and it will show you basic statistics through stdout. 

If you don't want to change the code or the above change does not show the statistics, then you may want to put a printing statement after line 203. We probably want to see MUMPS_PAR%INFOG(5), INFOG(11) and RINFOG(3). These will show biggest frontal matrix (estimation and actual one) and total GFLOP. Also, you need to print MUMPS_PAR%N and NNZ. These are required to understand why BLIS shows different performance against openblas.

**Comment by cosstas** [comment]
@kyungjoo-kim Here is the output from the first iteration (by commenting lines 74&75) for BLAS and BLIS runs separately:
[mumps_blas_log.txt](https://github.com/flame/blis/files/3070076/mumps_blas_log.txt)
[mumps_blis_log.txt](https://github.com/flame/blis/files/3070077/mumps_blis_log.txt)

**Comment by kyungjoo-kim** [comment]
@cosstas  Thanks. It looks like that something really went wrong. 
```
Symbolic Phase 
- It looks similar as this phase does not involve with BLAS nor LAPACK
===================================================
BLAS: ELAPSED TIME IN ANALYSIS DRIVER=       0.1241
BLIS: ELAPSED TIME IN ANALYSIS DRIVER=       0.1575

Numeric Phase (Factorization)
- 5x difference between BLIS and OpenBLAS
- note that the maximum frontal matrix size is "300". 
======================
BLAS:  ELAPSED TIME IN FACTORIZATION DRIVER=       0.0974
BLIS:  ELAPSED TIME IN FACTORIZATION DRIVER=       0.4896

Solve Phase (forward/backward solves)
- 5x difference
============================
BLAS:  TIME in solution step (fwd/bwd)  =       0.005242
BLIS:  TIME in solution step (fwd/bwd)  =       0.025828
``` 

First of all, the biggest frontal matrix size is 300 and the number of tree nodes is 5175. It means that you have many tiny problems well below 300. If you do 22128/5175 =  4.27, this means on average each tree node has 4 rows. As the elimination tree has a small number of rows nearby leaf nodes, I would say most of the tree node has a single row operations.

Considering that the factorization and the solve phases has the similar performance difference, the difference is probably comes from some sort of "overhead" in terms of function calls and packing. 
In my opinion, your problem size indicates that BLIS may have relatively more overhead compared to open blas per each function call. 

This might be due to that BLIS has a more layered software structure. I am not sure if open blas has some specialization in tiny matrices to remove such overhead of the functions. @fgvanzee how do you think  ?

**Comment by kyungjoo-kim** [comment]
BTW, my comment in the above assumes that you did not do any mistake in the blis configuration and setting threading environment variables. It might be good that blis provides some comparison when tiny problem blas functions are called many times (in this case, a relevant problem sizes are probably 1x10 and 3x40 for 5000 times).

**Comment by devinamatthews** [comment]
I'll just leave [this](https://gist.github.com/devinamatthews/168e178a79ffdf8f2a903397603c6ffe) here...

**Comment by fgvanzee** [comment]
@kyungjoo-kim Thank you for your computational forensics efforts! :)

Currently, BLIS does not make any special attempt to handle cases that involve small or skinny matrix operands, and therefore, if the problem sizes being computed are anything close to 4x4, or 1x10, or 3x40, performance will definitely suffer. This is because BLIS goes through the same motions for large matrix problems, which involves (most notably) packing, but also other kinds of overhead.

So, for now, benchmarks that execute many small problems will not do well when linked to BLIS.

**Comment by cosstas** [comment]
@kyungjoo-kim 
The previous MUMPS logs were from an 'example/test' case. I include results from an actual case, which is much bigger:
[mumps_blas_log_2.txt](https://github.com/flame/blis/files/3072218/mumps_blas_log_2.txt)
[mumps_blis_log_2.txt](https://github.com/flame/blis/files/3072219/mumps_blis_log_2.txt)
It appears that the issue you described in independent to the mesh size and it boils down to the fact that BLIS is made for big things... :-)
If you ever tweak BLIS for problems like my case, I'll be happy to give it a try.

**Comment by kyungjoo-kim** [comment]
@cosstas 

1. if your code uses the so-called standard FE scheme, the matrix should be symmetric. Why do you use "LU Solver for unsymmetric matrices" ? Just wondering. 

2. The largest frontal matrix is now 1082 and # of total tree nodes is 94747.
```
BLAS ELAPSED TIME FOR FACTORIZATION           =      0.8358
BLIS ELAPSED TIME FOR FACTORIZATION           =      0.6065
```
Now, the situation is better than your example problem and the difference is also reduced. The factorization phase shows 37% difference between open BLAS and BLIS. I guess that your BLIS library is configured and built correctly. You can see the almost the same performance if you can test even a bigger problem. This might not be very meaningful anyway as you are not going to solve such a large problem in practice. 

3. Solve cost seems to behave in a similar way to the smaller problem case. 
```
 TIME in solution step (fwd/bwd)  =       0.057961
 TIME in solution step (fwd/bwd)  =       0.306117
 ```
As I am not a developer of open blas nor blis, I am not sure where the performance difference comes from. I believe that BLIS team does not have enough man power to optimize all BLAS kernels. The blis framework is smart and it reuses highly optimized level 3 micro kernels for most of level 3 functions. While they mostly focus on level 3 functions, the other level 2 and level 1 functions may not be optimized as much as other BLAS libraries.

I don't have a BLIS tweak and am not a BLIS developer. I know that improvements for the small problem sizes and leve1/2 functions are on their worklist but they also have other work items.

**Comment by cosstas** [comment]
@kyungjoo-kim 
>     1. if your code uses the so-called standard FE scheme, the matrix should be symmetric. Why do you use "LU Solver for unsymmetric matrices" ? Just wondering.

I haven't developed the solution methodology, so I can't really comment. However, the code appears to have options for both symmetric and unsymmetric matrices (solve_mumps_par.F, lines 64-69):
`     IF(TYPEXT.EQ.'S') THEN
        MUMPS_PAR%SYM = 2
      ELSE
        MUMPS_PAR%SYM = 0
      ENDIF`

Thank you for your remarks, they 've been very educational for me. I am looking for further BLIS development.
