### ISSUE TITLE
GCC restrict warning

### ISSUE THREAD

**Issue by loveshack** [flame/blis#328]
It looks as if I never reported warnings from the Fedora build which may be significant:

ref_kernels/ind/bli_gemmtrsm4m1_ref.c:221:1: warning: passing argument 2 to restrict-qualified parameter aliases with argument 5 [-Wrestrict]

Sample complete build output: https://kojipkgs.fedoraproject.org//packages/blis/0.6.0/2.fc31/data/logs/x86_64/build.log

I haven't checked an optimization report, but I guess gcc will ignore the qualifier, having spotted the aliasing.

**Comment by fgvanzee** [comment]
@loveshack Thanks for this report. From line 184 of `ref_kernels/ind/bli_gemmtrsm4m1_ref.c`:
```
    rgemm_ukr \
    ( \
      k, \
      one_r, \
      a1x_i, \
      bx1_i, \
      one_r, \
      b11_r, rs_b, cs_b, \
      data, \
      cntx  \
    ); \
```
Maybe the takeaway here is that `gemm` interfaces that would otherwise want to use `restrict` should generally not do so for `alpha` and `beta` parameters? Seems like passing in the address of the same variable (set to 1) for both would be a scenario that wouldn't be difficult to stumble upon.

**Comment by devinamatthews** [comment]
If you go by [this](https://stackoverflow.com/questions/20653893/is-it-legal-to-alias-const-restrict-pointer-arguments) then the way that `restrict` is used here should be fine. Also, since the source is compiled in its own translation unit any aliasing noticed by the compiler in another translation unit shouldn't affect the optimizations applied (the corollary is that inline functions with `restrict` are another story).

To be more specific: I would advise that *all* pointers for which you can guarantee that no pointer *write* aliases with another pointer read or write should be marked restrict. I would further advise that restrict is also OK when the pointer ranges for a read and write *perfectly overlap* (e.g. `axpy`), but the standard may not explicitly address this.

**Comment by fgvanzee** [comment]
Thanks for chiming in, Devin. My interpretation, then, is that gcc being a little overzealous with its `restrict` checking.

@loveshack I'll still apply a small hack to that file to pacify gcc, but I think Devin makes a good point: the compiler shouldn't complain if it sees you passing in the same address into two `restrict` pointers as long as the pointed-to memory is not modified.

**Comment by devinamatthews** [comment]
Well, the compiler is simply erring on the side of caution. For example, the function:

```C
double crazy_dot(int n, const double* restict a, const double* restrict b)
{
    double sum = 0;
    for (int i = 0;i < n;i++)
    {
        ((double*)b)[i] = 1;
        sum += a[i]*b[i];
    }
    return sum;
}
```

is perfectly legal C99. Because of the restrict, the compiler is free to cache the value of `a[i]` before the write to `b[i]`, whereas it couldn't if restrict were not present. If you pass the same array as both `a` and `b` then the behavior would differ for restrict or no restrict. Since the compiler doesn't know you aren't doing insane things like that then it rightly complains.

**Comment by fgvanzee** [comment]
Sorry for the broken commit. Forgot to write out file before commit. 0cd383d should work now.

**Comment by loveshack** [comment]
If you think GCC is issuing bad diagnostics, please make a bug report.

-fopt-info will probably reveal what it does, like possibly ignoring
restrict and not vectorizing.

**Comment by devinamatthews** [comment]
I don't think its a bad diagnostic, just that the compiler has no way of knowing the call was actually safe. If Field's patch removes the warning, let us know and we can close the issue.

**Comment by devinamatthews** [comment]
Should be fixed, reopen if not.
