### ISSUE TITLE
Does `dim_t` need to be `gint_t` ?

### ISSUE THREAD

**Issue by hominhquan** [flame/blis#337]
Hi all,

Just a rationale question, is `dim_t` (dimension) necessarily to be a `gint_t` signed integer ? Is there any harm if we change it to `guint_t` ? I see good reason for `inc_t` and `doff_t` to be possibly negative, but not for the matrix dimension.

Quan

**Comment by fgvanzee** [comment]
@hominhquan You raise a fair point. In fact, in earlier versions of BLIS, `dim_t` **was** defined in terms of `guint_t`. However, I decided to redefine it as `gint_t`. I forget what the "tipping point" issue of the day was for us (maybe @devinamatthews or @jeffhammond remember?), but I can give you one great example of where the signedness comes in handy. Consider the following loop that iterates backwards through an array/matrix:
```c
for ( dim_t i = n - 1; 0 <= i; i-- )
{
   // some computation in terms of i.
}
```
This loop (or at least this particular implementation of the loop) would not be possible if `dim_t` were unsigned because the moment `i` is decremented from 0 it wraps around to its maximum value, which is clearly not what we need (and would prevent the loop from ever terminating). Of course, you could imagine some workaround:
```c
for ( dim_t i = n; 1 <= i; i-- )
{
   // some computation in terms of (i - 1).
}
```
But this is, in my opinion, ugly and obfuscating. Yes, we do give up half of the possible range with signed integers, but many (most?) systems define `gint_t` as a 64-bit integer, and so even with that reduction in range, there are plenty of bits left to work with and thus it likely would not affect very many applications. Also, the BLAS API uses signed integers (usually 32-bit, if I'm not mistaken), so many in the community are already accustomed to this limitation.

**Comment by devinamatthews** [comment]
@fgvanzee I also agree that signed integers are better for dim_t (avoids the many unexpected underflow problems that *will* occur; 2x range of unsigned isn't really a big deal especially for 64 bit). But on the off chance that I might run across unsigned numbers, I always write my reverse loops using the "goes to" operator:

```C
for (dim_t i = n;i --> 0;)
{
    //...
}
```
Of course `i --> 0` is just `i-- > 0`.

**Comment by fgvanzee** [comment]
@devinamatthews Cute trick. Not crazy about it for readability purposes (it kind of makes the uninitiated stare at it for a while to convince themselves of what it actually does), but definitely convenient if you are unsure of signedness. Thanks for sharing.

**Comment by jeffhammond** [comment]
I remember some weird stuff with integer types in loop bounds on Xeon Phi
but it has been years and I can’t remember which was best.

I think Devin’s trick is evil and he should use C++20 ranges instead but I
have not written any code in the past month so I have no credibility here.
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by hominhquan** [comment]
Thanks @fgvanzee and @devinamatthews for pointing out the use of `dim_t` in reverse loop. Ok for me now for `dim_t` to be signed.
