### ISSUE TITLE
checkblas failures with generic target

### ISSUE THREAD

**Issue by loveshack** [flame/blis#342]
I built current master on power8 ppc64le (Fedora 29) with
```
CFLAGS=-mcpu=power8 ./configure generic
```
and got the following failures from checkblas, though checkblis passed:

```
cblat2:

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .367133    ,    .442557    )  (    .367133    ,    .442557    )
       2  (    .619742    ,    .145569    )  (    .619742    ,    .145569    )
       3  (    .419282    ,   -.274696    )  (    .419282    ,   -.274696    )
       4  (    .113902    ,   -.162085    )  (    .497250E-01,    .797809E-01)
       5  (    .438563E-01,    .402786    )  (    .438562E-01,    .402786    )
       6  (    .939156    ,    .138420    )  (    .664142    ,   -.405661    )
       7  (    .455686    ,   -.675104E-01)  (    .455686    ,   -.675104E-01)
       8  (   -.154942E-02,    .266114    )  (   -.150000E+11,    .602897E+10)
       9  (   -.938862E-01,    1.08419    )  (   -.938862E-01,    1.08419    )
 ******* CTPMV  FAILED ON CALL NUMBER:
    219: CTPMV ('L','N','U',  9, AP, X, 2)                                      .

 ******* FATAL ERROR - COMPUTED RESULT IS LESS THAN HALF ACCURATE *******
                       EXPECTED RESULT                    COMPUTED RESULT
       1  (    .277223    ,   -.348651    )  (    .185920E+10,    .546762E+12)
       2  (    .806693    ,   -.492507    )  (   -.940210E+09,    .547188E+12)
       3  (    .966533    ,    .442557    )  (   -.228236E+09,   -.136729E+10)
       4  (     .00000    ,     .00000    )  (   -.677304E+09,   -.137215E+09)
       5  (    .926573    ,    .106893    )  (    .197802E+20,   -.154845E+20)
       6  (    .956543    ,   -.100899    )  (    .239256E+09,   -.503443E+10)
       7  (    .686813    ,   -.156843    )  (    .176324E+10,    .214785E+09)
       8  (    .247253    ,   -.292707    )  (    .247253    ,   -.292707    )
       9  (    .774226E-01,    .989011E-01)  (    .774226E-01,    .989011E-01)
 ******* CTPSV  FAILED ON CALL NUMBER:
    195: CTPSV ('U','N','U',  9, AP, X, 2)                                      .

cblat3:

 CHEMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* CHEMM  FAILED ON CALL NUMBER:
    256: CHEMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

 CSYMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* CSYMM  FAILED ON CALL NUMBER:
    256: CSYMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

zblat3:

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* ZHEMM  FAILED ON CALL NUMBER:
    256: ZHEMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .

 ZSYMM  PASSED THE TESTS OF ERROR-EXITS

 ******* FATAL ERROR - PARAMETER NUMBER 11 WAS CHANGED INCORRECTLY *******
 ******* ZSYMM  FAILED ON CALL NUMBER:
    256: ZSYMM ('L','U',  1,  1,( 1.0,  .0), A,  2, B,  2,(  .0,  .0), C,  2)    .
```

Then I checked the generic config on skx with -march=skylake-avx512, and also with -march=haswell, and got similar results.

I guess #341 is related.

**Comment by fgvanzee** [comment]
@loveshack I suspect that #329 also falls under this umbrella.

What compiler and version are you using?

**Comment by loveshack** [comment]
Sorry, I should have recorded the compiler, but it isn't that.

The ppc64 failure was with gcc 8.3 (Fedora 29).  I see variations on
these failures also with gcc 6.3/sandybridge, 7.4/haswell, 8.3/skx,
8.3/haswell, and 9.1/sandybridge; also with clang-6.0/haswell.

I think it needs debugging.  I don't _think_ it was a problem in the
past when I was trying the generic kernel with -ffast-maath, but I'm not
certain I ran checkblas as well as the full blis test.

**Comment by fgvanzee** [comment]
@loveshack Would you have run `make check`? `checkblas` would have been executed automatically by the `check` target.

**Comment by loveshack** [comment]
I typically run check, and that's how I saw the problem originally, but
I've been running checkblas directly to investigate this for different
configurations.

**Comment by loveshack** [comment]
I got round to finding out where checkblas started failing with the generic target (tested on x86_64).  It's at commit 31c8657f. (Automated bisection fails because of one or more commits that don't build.)
I haven't tried on arm64 to see if #341 is the same.

**Comment by fgvanzee** [comment]
@loveshack Thanks, Dave. I'll look into this.

**Comment by loveshack** [comment]
I don't currently get the cblat2 failure on x86 (haswell) -- I haven't
re-tried power8 -- and that #341 appears to be different (unless they're
bot somehow due to optimizing undefined behaviour, or similar).

**Comment by fgvanzee** [comment]
@loveshack Thanks for your patience on this. We've been abnormally busy with other priorities.

I got a chance to look at this issue. Thanks to your bisection (and to the fact that I was able to reproduce on my end with `generic` on a Haswell-era system), I was able to quickly identify the offending code changes and revert them after realizing that they were never appropriate to begin with.

The problem was that I tried to homogenize some code in `bli_hemm_front.c` and `bli_symm_front.c` to look like similar code in `bli_gemm_front.c`, except that this was one of those cases where the codes *needed* to be different (and, to make this downright comical, I can't seem to find the offending code line in the case of `gemm` anyway, so really it seems I was *de*-homogenizing `hemm` and `symm`?).

Now bear with me, because this is complicated.

The offending line is the the first line in the following snippet:
```c
    // An optimization: If C is stored by rows and the micro-kernel prefers
    // contiguous columns, or if C is stored by columns and the micro-kernel
    // prefers contiguous rows, transpose the entire operation to allow the
    // micro-kernel to access elements of C in its preferred manner.
    if ( !bli_obj_is_1x1( &c_local ) )
    if ( bli_cntx_l3_vir_ukr_dislikes_storage_of( &c_local, BLIS_GEMM_UKR, cntx ) )
    {
        bli_toggle_side( &side );
        bli_obj_toggle_conj( &a_local );
        bli_obj_induce_trans( &b_local );
        bli_obj_induce_trans( &c_local );
    }
```
The conditional body being considered is one we want to execute when the IO preference of the microkernel doesn't match the storage of C. (Many microkernels only implement either row **or** column IO **plus** a general stride case that catches true general stride, e.g. tensors, as well as the contiguous storage that happens to be the opposite of the one that is preferred--row or column. So if there is a mismatch, we logically transform the operation so the mismatch effectively disappears.)

Now, before we go on, it is important to know that the kernels used by the `generic` subconfiguration are the reference kernels. The reference kernels are registered as being row-preferential. 

Going back to the above code, the "don't optimize in cases of 1x1 C" exception wasn't appropriate in the case of `hemm` and `symm`. The reason? The 1m method was actually being activated here. Why? Because 1m is always activated when the complex-domain microkernels that are registered are reference kernels. In the case of `generic`, this condition is met, and so 1m is triggered. (In theory, this condition could be tightened up so that 1m only activates if the corresponding real-domain microkernel is *not* a reference microkernel--that is, only if the real-domain microkernel was "optimized" or "custom". The 1m method wasn't really meant to utilize reference kernels, though it isn't fundamentally incompatible with them either.)

The thing about 1m is that, for reasons that are documented in the 1m paper, suddenly it becomes absolutely critical that the IO preference of the microkernel be matched to the storage of matrix C. And that brings us back to the offending line I showed above. That "don't optimize in cases of 1x1 C" exception was sabotaging 1m by allowing the preference to mismatch the storage of C (recall that BLAS only tests column storage, but our reference microkernel prefers row IO), but only for the cases where C is 1x1.

It turns out that `trmm` was also using this ill-advised `if ( !bli_obj_is_1x1( &c_local ) )` exception, but that operation wasn't affected because of the absence of *another* optimization that is specific to 1m via level-3 operations that use the `gemm` macrokernel (ie: `gemm`, `hemm`, and `symm`), and also because `trmm` inherently uses beta = 0, which is always real (the bug doesn't manifest when beta has a non-zero imaginary component because the aforementioned `gemm`-specific optimization is then bypassed out of technical necessity--another detail documented in the 1m paper). Nonetheless, I will remove that exception from `trmm` along with `hemm` and `symm`.

And the level-3 BLAS test driver failures that were triggering were isolated to 1x1 `hemm` and `symm` test cases.

Thank you, Dave, for helping us identify this very subtle, very long-tailed bug.

PS: I could not reproduce the `out.cblat2` errors for `ctpmv()` and `ctpsv()`
