### ISSUE TITLE
use best available gemm/trsm rather than falling back to generic

### ISSUE THREAD

**Issue by jeffhammond** [flame/blis#368]
Both AVX-512 ports of BLIS lack complex gemm and gemmtrsm support, but the Haswell port has optimized complex gemm and optimized real gemmtrsm.

I propose to have the SKX and KNL configs use the HSW kernels that exist, rather than falling back on the generic C99 versions.  On the Ice Lake client platform, this will improve the performance of cgemm and zgemm by approximately 4x.

In the table below, I've added capital letters to indicate the cases that should fall back to Haswell rather than Generic.

| Vendor/Microarchitecture             | BLIS sub-configuration | `gemm` | `gemmtrsm` |
|:-------------------------------------|:-----------------------|:-------|:-----------|
| Intel Knights Landing (AVX-512/FMA3) | `knl`                  | `sdCZ`   |   `SD`         |
| Intel SkylakeX (AVX-512/FMA3)        | `skx`                  | `sdCZ`   | `SD`           |

I am not particularly savvy on the BLIS build system, but I expect that this feature request is trivial for @fgvanzee or @devinamatthews to implement.

**Comment by devinamatthews** [comment]
@fgvanzee or `1m`?

**Comment by fgvanzee** [comment]
@devinamatthews Yes, unless I'm missing something, this issue is moot.

@jeffhammond Take a look at the SkylakeX results available in the [Performance.md](https://github.com/flame/blis/blob/master/docs/Performance.md#skylakex-results) document. What you'll find is that all level-3 operations perform more-or-less as expected for all level-3 operations.

For example, single-threaded `cgemm` and `zgemm` perform on-par with single-threaded `sgemm` and `dgemm`, respectively. *But wait*, you say, *how can this be if the `skx` subconfiguration only registers optimized `sgemm` and `dgemm` microkernels*? Wouldn't the generic/reference/C99 `cgemm` and `zgemm` microkernels deliver abysmal performance? Yes, they would, but the `skx` subconfiguration doesn't use reference microkernels for complex domain problems. Instead, it uses (minor brag) my personal favorite BLIS innovation to-date--the 1m method--to induce (emulate) support for matrix multiplication in the complex domain using only real domain microkernels. BLIS automatically activates the 1m method whenever the following three conditions are met:
- a complex level-3 operation is invoked,
- the active subconfiguration's registered **complex** domain `gemm` microkernel is a reference microkernel, *and*
- the active subconfigurations's corresponding registered **real** domain microkernel is NOT a reference microkernel (in which case we assume it is optimized in assembly).

For more information on how this 1m black magic is possible, please read my paper on the subject, which can be found in the [Citations](https://github.com/flame/blis#citations) section of the BLIS `README.md`. (I just updated the link to the latest draft.) Also, feel free to ask questions if you have any, or to challenge me if you think I'm still wrong. :)
