### ISSUE TITLE
Avoid sorting LDFLAGS

### ISSUE THREAD

**Issue by isuruf** [flame/blis#373]
I wanted to add a couple of flags `-Xclang --dependent-lib=msvcrt` which has to come in that order, but BLIS's Makefiles sorts them. https://github.com/flame/blis/blob/e67deb22aaeab5ed6794364520190936748ef272/common.mk#L813-L814

**Comment by fgvanzee** [comment]
@isuruf The `sort` function is being used here only because we want the ability to remove duplicates. I agree that sorting is not actually what we want.

I will fashion a workaround using the "recursive" solution proposed in [this stackoverflow thread](https://stackoverflow.com/questions/16144115/makefile-remove-duplicate-words-without-sorting).

**Comment by devinamatthews** [comment]
@fgvanzee Do you *actually* need to remove duplicates?

**Comment by isuruf** [comment]
Removing duplicates is also problematic. For eg: `-L /usr/lib -L /usr/local/lib`  are valid and removing `-L` from one is wrong

**Comment by devinamatthews** [comment]
As many warts as they have, there is a reason that people wrote tools like autoconf and libtool 😃 .

**Comment by devinamatthews** [comment]
But not cmake. Never cmake.

**Comment by fgvanzee** [comment]
> Removing duplicates is also problematic. For eg: `-L /usr/lib -L /usr/local/lib` are valid and removing `-L` from one is wrong

Hmm, good point. I think there are *other* situations where I do want to remove duplicates (because they don't involve compiler flags). But this (`LDFLAGS`) certainly seems like a situation where duplicates can be left alone.

> But not cmake. Never cmake.

I continue to be astonished at how many projects seem to disagree (or simply not care).

**Comment by fgvanzee** [comment]
@isuruf Try working with d626112. Hopefully that allows you to add your `-Xclang --dependent-lib=msvcrt` flags.

**Comment by isuruf** [comment]
Thanks. Works for me.
