### ISSUE TITLE
Blis dgemm crashing on Skylake X on [512x512] matmult [512x512]

### ISSUE THREAD

**Issue by assaad** [flame/blis#375]
When i try a dgemm of  [512x512] matmult [512x512] on skylake X, my computer restarts. 
If i try the same using the generic blas it's slower but the computer doesn't crash. 
Any idea on how to help you to fix this issue? 
My cpu model is: i7-7820X CPU
Thanks

**Comment by assaad** [comment]
For info i compiled the library using the following config: 
./configure --quiet --without-memkind --disable-mixed-dt-extra-mem --disable-mixed-dt --enable-cblas --enable-blas --disable-threading --disable-shared --enable-static skx

I need the enable-cblas option. 
Many thanks!

**Comment by assaad** [comment]
Just for info: I tried release 0.6.0 and release 0.6.1, both crashed on skx config, and both succeeded on haswell.

**Comment by fgvanzee** [comment]
@assaad Thanks for this report, and sorry you're having issues with BLIS on SkylakeX.

I'll try to reproduce this next week.

**Comment by devinamatthews** [comment]
Sounds like it could be a thermal stability issue.

**Comment by jeffhammond** [comment]
@assaad
1. Can you please try MKL (https://software.intel.com/en-us/mkl/choose-download) to see if this has anything to do with BLIS?
2. What OS is this?
3. Full details to reproduce this would be helpful.  Is this 100% reproducible?

@devinamatthews 512x512 is a pretty tiny computation to hit any sort of thermal limit, unless one is running it in a loop. The individual call takes ~0.2 milliseconds.

**Comment by fgvanzee** [comment]
Unfortunately I was unable to reproduce this issue using @assaad's `configure` options on a Xeon Platinum 8167M.

**Comment by assaad** [comment]
I am using manjaro OS and i7-7820X it has one fused add multiply and i read somewhere here that skx compilation needs at least 2, might that be the problem? is there a minimal test i could run again on my machine that might help?

**Comment by assaad** [comment]
An update: since last 2 days, i updated my OS, and i removed overclocking on my CPU, i run the test now and it's passing, might be thermal problem or OC. Anyway thanks very much!

**Comment by fgvanzee** [comment]
@assaad I'm glad you were able to solve your issue. (h/t to @devinamatthews for suggesting the possibility of overheating.)

> I am using manjaro OS and i7-7820X it has one fused add multiply and i read somewhere here that skx compilation needs at least 2, might that be the problem?

@assaad No, that should not be a problem. My understanding is that the `skx` kernel and subconfiguration does not **need** two FPUs (VPUs), but rather, it is **optimized** for two FPUs. It should still run fine on single FPU systems, but with a peak floating-point throughput per cycle of half that of dual FPU systems.

A similar situation exists with the `zen` subconfiguration, designed for Zen1 AMD microarchitectures. That subconfiguration uses the `haswell` kernels, which are tuned for Haswell-like microarchitectures that have two FPUs (or, more specifically, issuing two FMAs per cycle). Those kernels run fine on Zen1 hardware, which can only issue one FMA per cycle. However, they run at half the floating-point throughput per cycle.

There is only a problem if you use a kernel designed for fewer FPUs on a system with more FPUs. In that case, performance will suffer _unnecessarily_ since the kernel is not utilizing all of the hardware's floating point capacity.

But thankfully, in none of these cases would we expect crashing or unrequested rebooting. :)

**Comment by jeffhammond** [comment]
> An update: since last 2 days, i updated my OS, and i removed overclocking on my CPU, i run the test now and it's passing, might be thermal problem or OC. 

Yeah, don’t overclock and run AVX-512 code. There is a very good chance that is a very bad idea.
