### ISSUE TITLE
Spack package

### ISSUE THREAD

**Issue by naromero77** [flame/blis#381]
Are there plans for packaging up BLIS as a Spack package?

https://github.com/spack/spack

I would be willing to take a shot a it, if someone from the team was willing to contribute some time answering basic questions about the build system and reviewing the final package.

**Comment by fgvanzee** [comment]
@naromero77 Thank you for your interest in creating/maintaining a package for the BLIS community!

Another user, @s-sajid-ali, reported in issue #238 that he created an spack recipe. Perhaps you can leverage what he started? (I recommend reading through that issue discussion before you begin.)

We'll happily answer any questions you have.

**Comment by s-sajid-ali** [comment]
@naromero77  : [`BLIS`](https://spack.readthedocs.io/en/latest/package_list.html#blis) and [`AMDBLIS`](https://spack.readthedocs.io/en/latest/package_list.html#amdblis) and are already available in spack ! While I did take the initiative in creating the spack package for BLIS, lots of people have contributed to it since 2018.

**Comment by naromero77** [comment]
thanks, not sure how I missed the packages when I was looking earlier today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fgvanzee** [comment]
Glad this amounted to a no-op! :) Thanks @s-sajid-ali for chiming in.
