### ISSUE TITLE
Reconfigure should work correctly.

### ISSUE THREAD

**Issue by devinamatthews** [flame/blis#383]
After configuring once, running configure again with different settings should completely override the previous configuration. For example, on my machine, `./configure auto` misdetects the CPU type. Running `./configure haswell` afterwards (and completely rebuilding) does not override this wrong behavior though, although running that from the get-go is fine.

**Comment by fgvanzee** [comment]
Thanks for this report, Devin. This is super surprising to me. I was under the impression that the behavior you are asking for was already the status quo. I'll investigate.

**Comment by fgvanzee** [comment]
@devinamatthews Unfortunately I can't reproduce the "bad" `configure` behavior your reference. I tried (on a `haswell` machine):
```
$ ./configure auto; ./configure sandybridge; make
```
and
```
$ ./configure haswell; ./configure sandybridge; make
```
In both cases, a `sandybridge` library is built and the build system is left in a posture whereby its current "active" configuration is `sandybridge`:
```
$ make showconfig
configuration family:    sandybridge
sub-configurations:      sandybridge
requisite kernels sets:  sandybridge
kernel-to-config map:    sandybridge:sandybridge
```
The auto-detection branch in `configure` doesn't do anything special; it merely returns a sub-configuration name. So I can't see anything wrong there, either.

I think this issue is somehow specific to #385, though how I have no idea.

**Comment by devinamatthews** [comment]
Can you try it with a `make` between `configure`s?

**Comment by fgvanzee** [comment]
I tried:
```
./configure auto; make; ./configure sandybridge; make
```
and
```
./configure haswell; make; ./configure sandybridge; make
```
And the outcome was the same as previously, although here we end up with a `lib/haswell` directory with `haswell` libraries in addition to the `sandybridge` directory/libraries. (I did use `-j5` in all cases, but I assume that doesn't matter.)

**Comment by devinamatthews** [comment]
Given the revelations of #385, I think what happened is that I pulled one version *just before* you disabled the vectorized amaxv kernel, then cloned another *just after* and confusion ensued. I tried a coupled of other things using different kernels as markers and I think it does work as expected.

**Comment by fgvanzee** [comment]
Sorry that the stars aligned against you here. :-\ But ultimately I'm glad it was a no-op.
