### ISSUE TITLE
Question : does NodeJS binding exist?

### ISSUE THREAD

**Issue by Wandalen** [flame/blis#394]
Hello! First of all, thanks for this gem. I am very intrigued by the features of the project.
I have a question: does NodeJS binding exist for the project?

**Comment by devinamatthews** [comment]
I don't know much about NodeJS, but if there are existing bindings for BLAS then you could link BLIS on the backend instead of the system BLAS. At one time we has bindings for NaCl but then it was abandoned. I guess the equivalent nowadays is WebAssembly. Compiling BLIS into WebASM should be possible but we haven't done it as of yet.

**Comment by Wandalen** [comment]
@devinamatthews thanks for the answer. WebAssembly is actually too slow to use it in NodeJS. Because of that WebAssemply is for browsers only. Binding to the compiled native executable file is a much faster solution. I was asking about that. As I understand, there is no such. By the way, I am interested in using the project to steroid our [JS math](https://github.com/Wandalen/wMathMatrix). I hope to find time to do it in the future. Thanks for the answer!

**Comment by devinamatthews** [comment]
@Wandalen you could try compiling BLIS as the backend for this https://github.com/NaturalNode/node-lapack.

**Comment by Wandalen** [comment]
Thanks for the link. It's really useful!
