### ISSUE TITLE
How should I configure if I use AMD CPU.

### ISSUE THREAD

**Issue by feifeibear** [flame/blis#405]
Here are specifications of my cpu. Now I am using the following command to configure.
Is that right?
```
./configure --enable-threading=openmp --enable-cblas --prefix=${CMAKE_CURRENT_BINARY_DIR}/blis zen
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           113
Model name:                      AMD Ryzen 7 3700X 8-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2105.281
CPU max MHz:                     3600.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        7186.44
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP always-on, RSB filling
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_ap
                                 icid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skini
                                 t wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt c
                                 lwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decode
                                 assists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

**Comment by BhaskarNallani** [comment]
./configure --enable-threading=openmp --enable-cblas --prefix=${CMAKE_CURRENT_BINARY_DIR}/blis auto

Instead of zen or zen2,  you can also give "auto" so that it select the configuration based on your processor core and builds.

You can also use **https://github.com/amd/blis**  repo which is fine tinned for latest AMD platforms.

**Comment by fgvanzee** [comment]
@feifeibear Thanks for your question. I can't offer the best support for Zen2 systems because I haven't yet had the chance to test BLIS on Zen2 (though I hope that changes in the near future).

In theory, @BhaskarNallani is right; you would want to either use `auto` as the configuration target or specify `zen2`. (Both options should lead to `zen2` being selected.) The problem is that I've not been able to independently confirm that the blocksize parameters determined by AMD are near-optimal. They probably work well enough, though.

**Comment by feifeibear** [comment]
cool, thanks fgvanzee and BhaskarNallani. `auto` is a good option.

**Comment by tuxzz** [comment]
Remember to remove `-march` or `-mtune` from CFLAGS if you defined them, or you will get a compilation error with `auto`.
`-flto` has no problem with my testing,  which gains a little performance(about 30GFLOPS for SGEMM @ 8thread).
