### ISSUE TITLE
Link Library Question

### ISSUE THREAD

**Issue by johnduffymsc** [flame/blis#430]
Hi

Apologies if this is too Debian/Ubuntu specific...

In my ```/usr/lib/aarch64-linux-gnu/blis-serial``` directory I have...
```
lrwxrwxrwx 1 root root      12 Feb 13 02:26 libblas.so -> libblas.so.3
-rw-r--r-- 1 root root 2411064 Feb 13 02:26 libblas.so.3
-rw-r--r-- 1 root root 2468408 Feb 13 02:26 libblis.so.3
```
What is the difference between the ```libblas.so.3``` and ```libblis.so.3```? I note they are slightly different in size.

The Debian/Ubuntu ```update-alternatives --config libels.so.3-aarch64-linux-gnu``` mechanism points to the ```libblas.so.3``` library. I was wondering why it doesn't point to ```libblis.so.3```.

Kind regards

**Comment by fgvanzee** [comment]
@johnduffymsc Sorry for the delayed response. You raise a good question. I *think* the two libraries are basically the same and that the reason there are two has to do with the "alternatives" system that Debian and Ubuntu use to switch between various BLAS implementations. I think the idea is that no matter which implementation you install (OpenBLAS, BLIS, etc.), the library files are named according to a standard convention, which allows the alternatives system to expose the library to the rest of the system in a consistent way without having to encode the various implementations' naming conventions (`libopenblas.so`, `libblis.so`, etc.) within the alternatives system's scripting logic.

Now, since BLIS implements a superset of the BLAS, it exports the BLAS API but also provides other APIs not present in any other implementation. That's why you see a `libblis.so` in addition to the `libblas.so`. The latter is there, again, mostly for the alternatives system so that it can use a comment name. If you installed vanilla BLIS from github, you would only see `libblis` files (though it contains BLAS symbols).

M. Zhou (@cdluminate), who maintains BLIS within the Debian/Ubuntu and Gentoo ecosystems, should be able to comment in more detail and correct anything I got wrong. He would know, for example, why there is a ~57K difference in the library files' sizes.

**Comment by cdluminate** [comment]
I'm the maintainer and I confirm that this point is Debian/Ubuntu specific.

The shared objects `libblas.so.3` and `libblis.so.3` from the package `blis-serial` provides exactly the same functionality, except for two differences:
1. They have different SONAMEs, `libblas.so.3` has `SONAME=libblas.so.3`, while `libblis.so.3` has `SONAME=libblis.so.3`. This is meaningful to maintain the alternatives mechanism when you build your programs against the BLAS/LAPACK library. If you symlink `libblis.so.3 (SOVERSION=libblis.so.3)` to `libblas.so.3`, and you link the program `foobar` against `libblas.so.3 (symlink)`, then `foobar` will look for `libblis.so.3` at runtime (see ld and ld.so manual for details)
2. the NON-BLAS ABIs are hidden in `libblas.so.3`. So the shared object is less likely able to mess up the namespace of dynamic linker.

**Comment by cdluminate** [comment]
FYI: https://salsa.debian.org/science-team/blis/-/blob/master/debian/patches/libblas-provider.patch

This is how the `libblas.so.3` is built. Anything is reproducible.

**Comment by cdluminate** [comment]
In brief we have to keep both `libblas.so.3` and `libblis.so.3` in the package to avoid making the mechanism fragile.

**Comment by johnduffymsc** [comment]
Thank you.
