### ISSUE TITLE
Raspberry Pi 4 Cluster Request for Comments/Feedback

### ISSUE THREAD

**Issue by johnduffymsc** [flame/blis#431]
Hi

As part of my MSc Scientific Computing at UCL, I have been doing some Linpack benchmarking of an 8 node Raspberry Pi 4 Model B cluster. I have posted some preliminary results in the README.md at:
```
https://github.com/johnduffymsc/picluster
```
These results are not the usual "Problem Size vs Gflops". I know in advance that I want to use a problem size utilising 80% of memory, so they are "NB vs Gflops". I'm trying to determine the optimum NB for a given problem size. I'm particularly interested in this because I want to make optimum use of the limited networking resources, whilst maintaining efficient load balancing.

Utilising a single core ```mpirun -host node1:1 -np 1 xhpl``` BLIS achieves full 80% R_peak utilising 80% memory, which outstrips OpenBLAS. But when running on 4 cores on a single node ```mpirun -host node1:4 -np 4``` the performance of BLIS drops off compared to OpenBLAS.

I would be grateful for comment/feedback, and hints to where I can improve/contribute to a Cortex-A72 kernel. 

I know the currently packaged Ubuntu BLIS uses the Cortex-A57 kernel, and currently there is no Cortex-A72 kernel. 

Please don't take too much notice of the multi-node results at the moment, I know I have some NET_RX softirq issues to resolve through NET_RX interrupt coalescing and NIC receive buffer increases. I know I can gain an additional 10Gflops across 8 nodes.

Kind regards

**Comment by rvdg** [comment]
John, 

My first question is whether you are familiar with how BLIS structures the matrix-matrix multiplication.  If not, it would be good to look into that, since how it is structured closely relates to what nb you should pick in HPL.  

Notice that, since it is your thesis, I am inclined to answer your questions with questions, so that you will gain the insight.

Robert

**Comment by johnduffymsc** [comment]
Hi Robert

Thank you for you reply.

Indeed, I will look into how BLIS structures matrix-matrix multiplication.

And point taken about answering with questions. I really appreciate any reply from the BLIS team.

Kind regards

John

________________________________

**Comment by rvdg** [comment]
The answer to the performance issues you are seeing is likely much deeper.  You need to understand a little about how HPL parallelizes the linear solve.  An ancient paper is 

https://www.osti.gov/biblio/10164371 <https://www.osti.gov/biblio/10164371>

(I think it actually appeared in JPDC).

You will then want to instrument the code to find out where time is being spent.  

Now, imho, this discussion forum is not really an appropriate place to be discussing all this, since many of the answers are less BLIS related and more related to HPL and how it interacts with BLAS libraries.  Once you understand all that, then you may want to come back with observations about how BLIS in particular interacts with HPL.

**Comment by johnduffymsc** [comment]
Hi Robert

All very much appreciated and taken onboard.

Thank you for your replies and time.

Best wishes

John

________________________________
