### ISSUE TITLE
DGEMM Segmentation Fault for certain input values

### ISSUE THREAD

**Issue by kvaragan** [flame/blis#460]
For input size m = 126 n = 1 k= 126 lda = 126, ldb=31509 and ldc=126 - the dgemm crashes.
The crash is not observed for smaller values of ldb.
The crash is observed in the kernel "bli_dgemmsup_rv_haswell_asm_1x6".
How to reproduce:
./configure --enable-cblas -t openmp auto 
make -j 
cd test
modified test_gemm.c to consider lda, ldb and ldc. Attaching test_gemm.c and test inputs.
Replace test_gemm.c with the file attached.
make -j blis
_$./test_gemm_blis.x crashIn.txt out.txt_
[test_gemm.zip](https://github.com/flame/blis/files/5588390/test_gemm.zip)
Crash observed from the commit id : **2605eb4d99d3813c37a624c011aa2459324a6d89**

**Comment by BhaskarNallani** [comment]
Fix:

Extra unnecessary load of A matrix in bli_dgemmsup_rv_haswell_asm_1x6 kernel causing segmentation issue. 
Looks like some copy paste error and need to check all other 1x6 kernels.
This may not be reproducible in testsuite because it always allocates multiple of 32 and no provision to test for leading dimension beyond size.

But when ldb=126 even though it is accessing beyond memory it is not giving issue this might be because that extra buffer might be part of B matrix which is till in blis heap. But when ldb is so big then B matrix is the end of blis heap and might be causing the issue.

--- a/kernels/haswell/3/sup/d6x8/bli_gemmsup_rv_haswell_asm_dMx6.c
+++ b/kernels/haswell/3/sup/d6x8/bli_gemmsup_rv_haswell_asm_dMx6.c
@@ -2828,7 +2828,6 @@ void bli_dgemmsup_rv_haswell_asm_1x6
        add(r10, rbx)                      // b += rs_b;

        vbroadcastsd(mem(rax        ), ymm2)
-       vbroadcastsd(mem(rax, r8,  1), ymm3)
        add(r9, rax)                       // a += cs_a;
        vfmadd231pd(ymm0, ymm2, ymm4)
        vfmadd231pd(ymm1, ymm2, ymm5)
@@ -2845,7 +2844,6 @@ void bli_dgemmsup_rv_haswell_asm_1x6
        add(r10, rbx)                      // b += rs_b;

        vbroadcastsd(mem(rax        ), ymm2)
-       vbroadcastsd(mem(rax, r8,  1), ymm3)
        add(r9, rax)                       // a += cs_a;
        vfmadd231pd(ymm0, ymm2, ymm4)
        vfmadd231pd(ymm1, ymm2, ymm5)
@@ -2862,7 +2860,6 @@ void bli_dgemmsup_rv_haswell_asm_1x6
        add(r10, rbx)                      // b += rs_b;

        vbroadcastsd(mem(rax        ), ymm2)
-       vbroadcastsd(mem(rax, r8,  1), ymm3)
        add(r9, rax)                       // a += cs_a;
        vfmadd231pd(ymm0, ymm2, ymm4)
        vfmadd231pd(ymm1, ymm2, ymm5)
@@ -2879,7 +2876,6 @@ void bli_dgemmsup_rv_haswell_asm_1x6
        add(r10, rbx)                      // b += rs_b;

        vbroadcastsd(mem(rax        ), ymm2)
-       vbroadcastsd(mem(rax, r8,  1), ymm3)
        add(r9, rax)                       // a += cs_a;
        vfmadd231pd(ymm0, ymm2, ymm4)
        vfmadd231pd(ymm1, ymm2, ymm5)
@@ -2914,7 +2910,6 @@ void bli_dgemmsup_rv_haswell_asm_1x6
        add(r10, rbx)                      // b += rs_b;

        vbroadcastsd(mem(rax        ), ymm2)
-       vbroadcastsd(mem(rax, r8,  1), ymm3)
        add(r9, rax)                       // a += cs_a;
        vfmadd231pd(ymm0, ymm2, ymm4)
        vfmadd231pd(ymm1, ymm2, ymm5)

**Comment by BhaskarNallani** [comment]
Another potential bug:

--- a/kernels/haswell/3/sup/d6x8/bli_gemmsup_rd_haswell_asm_dMx4.c
+++ b/kernels/haswell/3/sup/d6x8/bli_gemmsup_rd_haswell_asm_dMx4.c
@@ -1297,7 +1297,6 @@ void bli_dgemmsup_rd_haswell_asm_1x4
                                           // which would destory intermediate results.

        vmovsd(mem(rax       ), xmm0)
-       vmovsd(mem(rax, r8, 1), xmm1)
        add(imm(1*8), rax)                 // a += 1*cs_a = 1*8;

        vmovsd(mem(rbx        ), xmm3)

**Comment by fgvanzee** [comment]
@BhaskarNallani Thanks for these suggested fixes. I'll look to reproduce the bug and fix it.

**Comment by fgvanzee** [comment]
@kvaragan @BhaskarNallani I've pushed b43dae9a, which should fix both issues that Bhaskar identified. Thank you both for your assistance and patience.

**Comment by kvaragan** [comment]
Thanks Field.
