### ISSUE TITLE
How to switch to row-major?

### ISSUE THREAD

**Issue by Runkli** [flame/blis#483]
I'm using BLIS as an add on to an already existing app that uses linear algebra, however all matrices are stored in row major in the original app. I couldn't find a "switch" that I could use to use row-major instead so everything works together

**Comment by rvdg** [comment]
I assume you use BLIS through the traditional BLAS interface.  If so, then there are three options:


1) You recognize that storing a matrix by rows is the same as transposing it.  Thus, through some moderately clever mathematical trickery you can work with transposed matrices.

For example, if you compute C = A B you notice this is equivalent to computing C^T = ( A^T B^T ) = B^T A^T.  Hence, since the matrices are stored by rows, you would want to compute C = B A instead.


2) Switch to the BLIS typed API, which exposes row and column strides.  If you swap those strides, then you are done.

3) Use the BLIS object based API, which hides all such details altogether.  It is then a matter of setting the right settings when you create the matrices.

Robert

**Comment by Runkli** [comment]
Thank you so much, this helps a lot!

**Comment by rvdg** [comment]
Hopefully you noticed that my message should have said C^T = ( A B )^T...

**Comment by devinamatthews** [comment]
@Runkli also note that BLIS (optionally) exports a CBLAS interface which allows one to select row- or column-major.

**Comment by fgvanzee** [comment]
@Runkli And in case you ever forget the semantic meaning of row stride and column stride (some people struggle to remember), you can always find an explanation in the [FAQ](https://github.com/flame/blis/blob/master/docs/FAQ.md#im-used-to-thinking-in-terms-of-column-majorrow-major-storage-and-leading-dimensions-what-is-a-row-stride--column-stride).
