### ISSUE TITLE
How to get ILP64 BLIS

### ISSUE THREAD

**Issue by liushang0322** [flame/blis#700]
Direct make to get BLIS of LP64, how to get blis of ILP64

**Comment by xrq-phys** [comment]
Add option `-b 64` changes BLIS' F77 API to ILP64. c.f. `configure -h` output.

**Comment by liushang0322** [comment]
> Add option `-b 64` changes BLIS' F77 API to ILP64. c.f. `configure -h` output.

Thank you very much for your reply. I am a Julia user and also a beginner of BLAS. It seems that libblastranpoline can only switch and calculate the BLAS of ILP64. I want to know how an ordinary BLAS can be compiled into ILP64. Does this need to be in the source code? What to modify in , which makes me very troubled, I still can't correctly understand the switching method between LP64 and ILP64, even if it is only the difference in the symbol table from the outer layer

My trouble is that I now have a set of BLAS source code, which is compiled to LP64. He cannot successfully switch to Julia's openblas. I believe that the ILP64 compilation option should be made in blis. Is there a shortcut to switch from LP64 to ILP64? thanks

**Comment by xrq-phys** [comment]
LP64 and ILP64 are calling conventions instead of symbol differences, although Julia distinguishes them with a `64_` suffix, as is done in `libblastrampoline`.

You can refer to the [build script for blis_jll](/JuliaPackaging/Yggdrasil/tree/master/B/blis) for more information about Julia integration of BLIS or other BLAS implementations. And if I remember correctly `libblastrampoline` also does 32-bit forwarding somehow.
Anyways, this seem not the right place to discuss this topic. Symbol requirement by Julia is non-standard hence it's better to refer to Julia's side on patching BLAS backends.

**Comment by xrq-phys** [comment]
Btw we also have a public Discord server where questions on *using BLIS* for different purposes are discussed.

@fgvanzee I guess we can close this?

**Comment by fgvanzee** [comment]
Thanks for chiming in to help out the OP, @xrq-phys. Yes, we can close the issue.
