### ISSUE TITLE
Issue with the new blis library

### ISSUE THREAD

**Issue by kvaragan** [flame/blis#71]
I am running libflame benchmark test routine (test_libflame.x in test folder). the test gets aborted because FLA_Hemv_check() called from FLA_Hemv_external() reports "Detecting unequal object datatypes". Prior to this call the data is getting corrupted and culprit could be Trsm from the blis library.
Note: With older version of blis, the test suite works just fine.

Test Parameters are: single precision, row-major format, FLA_Chol_solve() corrupts the data due to the call to Trsm_external.

**Comment by fgvanzee** [comment]
@kvaragan
1. What BLIS configuration are you using, and on what kind of hardware?
2. What happens if you go through the same motions except with a reference build of BLIS?

**Comment by kvaragan** [comment]
@fgvanzee 
1. Kind of Hardware tried was haswell, carrizo & piledriver. BLIS Configuration _( --disable-threading --enable-cblas  <auto/carizzo/piledriver> )_
2. With older version of BLIS, the code just runs fine. No crashes/aborts. I notice some problem could be in the function **bli_trsm_lu_ker_var2()** of the **new blis**

**Comment by fgvanzee** [comment]
@kvaragan 
1. Are you saying that you tried each of those three configurations?
2. It would be helpful if you could give commit numbers instead of "old" versus "new". I know you are probably talking about before and after the big commit, but testing a specific commit before, and a specific commit after, and knowing for sure that that was the turning point would be good.
3. What leads you to believe that there is a problem in `bli_trsm_lu_ker_var2()`?

**Comment by kvaragan** [comment]
1.) Yes - on each of those hardwares.
2.) The commit number it was working fine was : **commit 0b126de1342c11c65623bcb38e258e21e9244e3d** I haven't tried the later versions before the big commit.
3.) When debugging I actually set the watch point for the variable _x datatype_. This value is getting changed in this function bli_trsm_lu_ker_var2(). Since its datatype is getting changed from what is created, later it leads to "Detecting unequal object datatypes" error.

**Comment by fgvanzee** [comment]
@kvaragan
Okay, I will begin by trying to reproduce this behavior. Let me get back to you. But just to clarify, this manifested when linking the libflame test suite to a BLIS library built from any of the three configurations you named, and running the Cholesky factorization test? Were you using default input parameters for the libflame test suite?

**Comment by kvaragan** [comment]
I noticed this problem in LU with pivot and QR_UT also. This problem occurs at the verification of the results. I used default parameters (input.global.general file) But I tried with different matrix sizes as well.

**Comment by fgvanzee** [comment]
@kvaragan I've been able to reproduce **a** problem, but I'm not sure if it's the same one that you are observing. I'll keep you informed.

**Comment by fgvanzee** [comment]
@kvaragan I found the source of the problem and corrected it in 4bcf1b3. The bug was consistent with your observation that the commits prior to the big commit (537a1f4) did not exhibit the problem. (However, I can't be sure that this was the *only* bug you were observing.) Please give it a try now and let me know how it goes.

**Comment by kvaragan** [comment]
@fgvanzee It worked, I checked it on haswell & piledriver. The test cases are passing now. Thank You
