### ISSUE TITLE
problem using only cblas interface

### ISSUE THREAD

**Issue by maganavi** [flame/blis#72]
If I only want to use the cblas interface so I only include cblas.h,  I get the error: ‘f77_int’ was not declared.

**Comment by fgvanzee** [comment]
@maganavi I think I fixed this in 97b512e. Please give it a try.
@devinamatthews If you have time, please review my changes in `frame/compat/cblas/src/cblas.h` and make sure I didn't do anything stupid. Note I left out the `#undef` for `F77_INT` and `F77_CHAR`, which appear in `bli_cblas.h`, since those macros do not appear in `cblas.h`.

**Comment by devinamatthews** [comment]
@fgvanzee That looks fine to me. The F77_INT and F77_CHAR macros will probably still have some effect (the CBLAS code may make internal copies of ints etc.), but I don't think that really matters.

**Comment by fgvanzee** [comment]
@devinamatthews Are you sure the `F77_INT` and `F77_CHAR` macros would have an effect? It appears that @maganavi wants to build BLIS with CBLAS support, install the library, and then compile his application code with `#include "cblas.h"` (and no `#include` for any BLIS-specific headers). Since BLIS will have already been built, I don't think the macros have any effect on the application code (since, again, those macros do not appear in `cblas.h`).

**Comment by devinamatthews** [comment]
Leaving them not #define'd or explicitly #undef'ed is fine, but if the 
user including cblas.h were to define these macros (for whatever reason) 
then it would affect the interface. For example,

#define F77_INT int

could potentially break if the internal BLAS interface is 64-bit. 
#undef'ing them makes CBLAS use f77_int and char always. So, either 
cblas.h could #undef them itself or the user could just not #define them 
to something nefarious.

**Comment by fgvanzee** [comment]
@devinamatthews Let's revisit this next week in-person.

**Comment by devinamatthews** [comment]
Here is a summary of what I'm trying to say:

`F77_INT` defined to: | Outcome *without* `#undef F77_INT` | Outcome *with* `#undef F77_INT`
---------------------------- | ---------------------------------------------------- | -----------------------------------------------
Not defined | OK, no internal conversion | OK, no internal conversion
Defined to the same type as f77_int | OK, but internal conversion done | OK, no internal conversion
Defined to something different | BAD, could be 32/64-bit mismatch | OK, no internal conversion

The third case is rather unlikely, but putting `#undef F77_INT` in `cblas.h` as well as (instead of?) in `bli_cblas.h` can't hurt...

**Comment by maganavi** [comment]
@fgvanzee Yes, That is what I want, the application shouldn't need to know anything about blis if it is using the cblas interface. @devinamatthews I think the building process can create a different cblas.h file with the correct f77_int definition according how the library was built.

**Comment by fgvanzee** [comment]
@maganavi I spoke with @devinamatthews and he now agrees with me: the `F77_INT` definition (as well as that of `F77_CHAR`) should not matter at all for an application that wants to simply `#include "cblas.h"`, because by that time, all of the code that uses those macros has already been compiled (they do not occur in `cblas.h`).

Have you been able to try out 97b512e (or one of its descendants? Please let us know if it still does not work for you, and if so, what problems remain.

**Comment by maganavi** [comment]
I  tried it today and It works fine.
